In [5]:
import numpy as np
import time


# Seed for reproducibility
np.random.seed(42)

# Create time array for every minute in 24 hours
time_in_minutes = np.arange(0, 1440)  # 0 to 1439

# Generate synthetic data
temperature = 22 + np.random.normal(0, 2, size=1440)
humidity = np.clip(55 + np.random.normal(0, 5, size=1440), 0, 100)
pressure = 1012 + np.random.normal(0, 1, size=1440)

# Combine all into a single array
data = np.column_stack((time_in_minutes, temperature, humidity, pressure))
np.set_printoptions(suppress=True, pre
print(data)

[[0.00000000e+00 2.29934283e+01 5.83144063e+01 1.00976177e+03]
 [1.00000000e+00 2.17234714e+01 6.08673693e+01 1.00987930e+03]
 [2.00000000e+00 2.32953771e+01 5.59051078e+01 1.01139313e+03]
 ...
 [1.43700000e+03 2.52146912e+01 5.16611022e+01 1.01312791e+03]
 [1.43800000e+03 2.29819499e+01 5.64609636e+01 1.01215449e+03]
 [1.43900000e+03 2.34697556e+01 5.40633549e+01 1.01166345e+03]]


In [2]:
# Basic Statistics
avg_temp = np.mean(temperature)
min_temp = np.min(temperature)
max_temp = np.max(temperature)
std_temp = np.std(temperature)

avg_hum = np.mean(humidity)
min_hum = np.min(humidity)
max_hum = np.max(humidity)
std_hum = np.std(humidity)

avg_pres = np.mean(pressure)
min_pres = np.min(pressure)
max_pres = np.max(pressure)
std_pres = np.std(pressure)
print("Basic Statistics:")
print(f"Avg Temp: {avg_temp:.2f}°C | Min: {min_temp:.2f}°C | Max: {max_temp:.2f}°C | Std: {std_temp:.2f}")
print(f"Avg Hum:  {avg_hum:.2f}%  | Min: {min_hum:.2f}%  | Max: {max_hum:.2f}%  | Std: {std_hum:.2f}")
print(f"Avg Pres: {avg_pres:.2f} hPa | Min: {min_pres:.2f} hPa | Max: {max_pres:.2f} hPa | Std: {std_pres:.2f}")

Basic Statistics:
Avg Temp: 22.08°C | Min: 15.52°C | Max: 29.71°C | Std: 1.97
Avg Hum:  55.13%  | Min: 39.90%  | Max: 70.97%  | Std: 4.89
Avg Pres: 1011.96 hPa | Min: 1008.99 hPa | Max: 1015.93 hPa | Std: 1.03


In [3]:
# Hourly Averages
temp_hourly = temperature.reshape(24, 60)
hum_hourly = humidity.reshape(24, 60)
pres_hourly = pressure.reshape(24, 60)

avg_temp_hourly = np.mean(temp_hourly, axis=1)
avg_hum_hourly = np.mean(hum_hourly, axis=1)
avg_pres_hourly = np.mean(pres_hourly, axis=1)

print("\nHourly Average Temperatures (°C):")
for hour, temp in enumerate(avg_temp_hourly):
    print(f"Hour {hour:02d}: {temp:.2f}")



Hourly Average Temperatures (°C):
Hour 00: 21.69
Hour 01: 21.99
Hour 02: 22.18
Hour 03: 22.11
Hour 04: 21.96
Hour 05: 22.08
Hour 06: 22.26
Hour 07: 21.99
Hour 08: 21.47
Hour 09: 22.00
Hour 10: 22.20
Hour 11: 21.83
Hour 12: 21.99
Hour 13: 22.18
Hour 14: 22.63
Hour 15: 22.19
Hour 16: 22.19
Hour 17: 22.13
Hour 18: 22.56
Hour 19: 21.91
Hour 20: 22.07
Hour 21: 22.08
Hour 22: 21.72
Hour 23: 22.50


In [4]:
# Anomaly Detection
threshold_temp = 25
minutes_above_25 = np.sum(temperature > threshold_temp)

min_temp_index = np.argmin(temperature)
min_temp_minute = time_in_minutes[min_temp_index]

# Convert minute to HH:MM format
min_temp_hhmm = time.strftime('%H:%M', time.gmtime(min_temp_minute * 60))


print(f"\nMinutes with temperature > 25°C: {minutes_above_25}")
print(f"Minimum temperature occurred at minute {min_temp_minute} ({min_temp_hhmm})")


Minutes with temperature > 25°C: 114
Minimum temperature occurred at minute 262 (04:22)
