In [ ]:
! Pip install numpy

### Part 1: Array Creation and Properties

In [ ]:
import numpy as np 

1. Create a 1D array named arr1d with integers from 0 to 9

In [ ]:
arr1d = np.arange(10)
print("arr1d:", arr1d)

arr1d: [0 1 2 3 4 5 6 7 8 9]


2. Create a 2D array named arr2d with shape (3, 3) filled with ones

In [ ]:
arr2d = np.ones((3, 3))
print("arr2d:\n", arr2d)

arr2d:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


3. Create random_matrix with random numbers from standard normal distribution

In [ ]:
random_matrix = np.random.randn(3, 3)
print("random_matrix:\n", random_matrix)

random_matrix:
 [[ 0.66325511 -1.0248142   0.80269271]
 [ 0.14513984  0.51722085  0.36074736]
 [ 1.80081613  1.11326884 -1.02643331]]


4. Create even_numbers from 10 to 50

In [ ]:
even_numbers = np.arange(10, 51, 2)
print("even_numbers:", even_numbers)

even_numbers: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


5. Create linspace_array with 7 values between 0 and 1

In [ ]:
linspace_array = np.linspace(0, 1, 7)
print("linspace_array:", linspace_array)

linspace_array: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


6. Find shape, ndim, and dtype of arr

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)
print("Dimensions (ndim):", arr.ndim)
print("Data type (dtype):", arr.dtype)

Shape: (2, 3)
Dimensions (ndim): 2
Data type (dtype): int64


### Part 2: Array Manipulation

1. Reshape arr1d (from Part 1) into a 2x5 2D array. Name the new array reshaped_arr

In [ ]:
reshaped_arr = arr1d.reshape(2, 5)
print("reshaped_arr:\n", reshaped_arr)

reshaped_arr:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


2. Transpose reshaped_arr. Name the result transposed_arr

In [ ]:
transposed_arr = reshaped_arr.T
print("transposed_arr:\n", transposed_arr)

transposed_arr:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


3. Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

v_stack = np.vstack((a, b))
print("Vertical Stack:\n", v_stack)

Vertical Stack:
 [[1 2 3]
 [4 5 6]]


4. Stack two 2D arrays m1 and m2 horizontally

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

h_stack = np.hstack((m1, m2))
print("Horizontal Stack:\n", h_stack)

Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]


5. Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts

In [ ]:
arr_to_split = np.arange(16).reshape(4, 4)

split_h = np.hsplit(arr_to_split, 2)
print("Horizontal Split - Left:\n", split_h[0])
print("Horizontal Split - Right:\n", split_h[1])

Horizontal Split - Left:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Horizontal Split - Right:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


6. Split arr_to_split vertically at index 2 (into first 2 rows and last 2 rows)

In [ ]:
split_v = np.vsplit(arr_to_split, [2])
print("Vertical Split - Top:\n", split_v[0])
print("Vertical Split - Bottom:\n", split_v[1])


Vertical Split - Top:
 [[0 1 2 3]
 [4 5 6 7]]
Vertical Split - Bottom:
 [[ 8  9 10 11]
 [12 13 14 15]]


### Part 3: Indexing, Slicing, and Boolean Indexing

1. Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2

In [ ]:
data = np.array([[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]])

element = data[1, 2]
print("Element at row 1, column 2:", element)

Element at row 1, column 2: 15


2. From data, extract the first two rows and all columns

In [ ]:
first_two_rows = data[:2, :]
print("First two rows:\n", first_two_rows)

First two rows:
 [[10 11 12]
 [13 14 15]]


3. From data, extract the elements 11, 15, and 17 using fancy indexing

In [ ]:
fancy_elements = data[[0, 1, 2], [1, 2, 1]]
print("Fancy indexed elements:", fancy_elements)

Fancy indexed elements: [11 15 17]


4. Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80

In [ ]:
scores = np.array([85, 92, 78, 65, 95, 88])
high_scores = scores[scores > 80]
print("Scores greater than 80:", high_scores)


Scores greater than 80: [85 92 95 88]


### Part 4: Numerical Operations and Aggregations

1. Element-wise multiplication and division of arr_op1 and arr_op2

In [ ]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])

multiplication = arr_op1 * arr_op2
division = arr_op1 / arr_op2

print("Element-wise multiplication:", multiplication)
print("Element-wise division:", division)

Element-wise multiplication: [ 20  80 180]
Element-wise division: [5. 5. 5.]


2. Calculate the sum of all elements in the matrix

In [ ]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

total_sum = matrix.sum()
print("Sum of all elements in the matrix:", total_sum)

Sum of all elements in the matrix: 45


3. Calculate the mean of each column in the matrix

In [ ]:
column_means = matrix.mean(axis=0)
print("Mean of each column:", column_means)

Mean of each column: [4. 5. 6.]


4. Apply a 10% discount to all prices using broadcasting

In [ ]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10

discounted_prices = price_array * (1 - discount_percentage)
print("Prices after 10% discount:", discounted_prices)

Prices after 10% discount: [ 90. 135. 180. 225.]
