<t1> Array Creation and Properties <t1/>

In [14]:
import numpy as np

In [15]:
aar1d = np.array([1, 2, 3, 4, 5, 6 , 7, 8, 9, 10])
print(aar1d)

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
aar2d = np.ones((3, 3)) 
print(aar2d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
random_matrix = np.random.randn(3, 3)
print(random_matrix)

[[ 0.2515414   1.28291515 -0.44582877]
 [-0.41072581  0.34336032  0.57594025]
 [ 1.20506925 -0.78765269  0.10433122]]


In [18]:
even_numbers = np.arange(10, 50, 2)
print(even_numbers)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [19]:
linspace_array = np.linspace(0, 1, 7)
print(linspace_array)

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [20]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
shape = arr.shape
print(shape)
ndim = arr.ndim
print(ndim)
dtype = arr.dtype
print(dtype)


[[1 2 3]
 [4 5 6]]
(2, 3)
2
int64


<t2> Array Manipulation <t2/>

In [24]:
arr1d = np.array([1, 2, 3, 4, 5, 6 , 7, 8, 9, 10])
reshaped_arr = arr1d.reshape(2, 5)
print(reshaped_arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [25]:
transposed_arr = reshaped_arr.T
print(transposed_arr)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_arr = np.stack((a, b), axis=0)
print(stacked_arr)

[[1 2 3]
 [4 5 6]]


In [27]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
horizontal_stack = np.hstack((m1, m2))
print(horizontal_stack)

[[1 2 5 6]
 [3 4 7 8]]


In [34]:
arr_to_split = np.arange(16).reshape(4, 4)
split_arrays1, split_arrays2  = np.hsplit(arr_to_split, 2)
print("Split arrays:\n", split_arrays1, "\n", split_arrays2)


Split arrays:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [35]:
split_arrays1, split_arrays2  = np.vsplit(arr_to_split, 2)
print("Split arrays:\n", split_arrays1, "\n", split_arrays2)

Split arrays:
 [[0 1 2 3]
 [4 5 6 7]] 
 [[ 8  9 10 11]
 [12 13 14 15]]


<t3> Indexing, Slicing, and Boolean Indexing </t3>

In [36]:
givendata = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
element = givendata[0, 1]
print(element)

11


In [37]:
first_two_rows = givendata[:2, :]
print(first_two_rows)

[[10 11 12]
 [13 14 15]]


In [38]:
selected_elements = givendata[[0, 1, 2], [1, 2, 1]]
print(selected_elements)

[11 15 17]


In [39]:
givenscores = np.array([85, 92, 78, 65, 95, 88])
above_80 = givenscores[givenscores > 80]
print(above_80)

[85 92 95 88]


<t4> Numerical Operations and Aggregations </t4>

In [40]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])
arr_mult = arr_op1 * arr_op2
arr_div = arr_op1 / arr_op2
print(arr_mult)
print(arr_div)


[ 20  80 180]
[5. 5. 5.]


In [43]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sum_of_elements = np.sum(matrix)
print(sum_of_elements)

45


In [44]:
mean_of_coulmns = np.mean(matrix, axis=0)
print(mean_of_coulmns)

[4. 5. 6.]


In [45]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10
price_after_discount = price_array * (1 - discount_percentage)
print(price_after_discount)

[ 90. 135. 180. 225.]
