In [16]:
import numpy as np


# Part1

Create a 1D array named arr1d with integers from 0 to 9.<br>

In [17]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create a 2D array named arr2d with shape (3, 3) filled with ones.<br>

In [18]:
arr2d = np.full((3,3), 1)
arr2d

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.<br>

In [19]:
random_matrix = np.random.randn(3, 3)
random_matrix

array([[-0.70935809,  0.9699762 ,  1.49446365],
       [-1.18210367,  0.06308109, -0.71614564],
       [ 1.82626474, -1.21918042, -0.22805837]])

Create an array named even_numbers containing even numbers from 10 to 50 (inclusive).<br>

In [20]:
even_numbers = np.arange(10, 51, 2)
even_numbers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).<br>

In [21]:
linspace_array = np.linspace(0, 1, 7)
linspace_array

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.<br>

In [22]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape of arr:", arr.shape)
print("Number of dimensions (ndim) of arr:", arr.ndim)
print("Data type (dtype) of arr:", arr.dtype)

Shape of arr: (2, 3)
Number of dimensions (ndim) of arr: 2
Data type (dtype) of arr: int64


# Part2

Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.

In [23]:
reshaped_arr = arr1d.reshape(2, 5)
reshaped_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Transpose reshaped_arr (from part 2 Q1). Name the result transposed_arr.


In [25]:
transposed_arr = reshaped_arr.T
transposed_arr

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.


In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
vstacked = np.vstack((a, b))
vstacked

array([[1, 2, 3],
       [4, 5, 6]])

Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.


In [28]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
hstacked = np.hstack((m1, m2))
hstacked

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.


In [35]:
arr_to_split = np.arange(16).reshape(4, 4)
left_half, right_half = np.hsplit(arr_to_split, 2)
print("left half:\n", left_half)
print("right half:\n",right_half)

left half:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
right half:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Split the array arr_to_split (from part 2 Q5 ) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.

In [36]:
top_half, bottom_half = np.vsplit(arr_to_split, [2])
print("Top half:\n", top_half)
print("bottom half:\n", bottom_half)

Top half:
 [[0 1 2 3]
 [4 5 6 7]]
bottom half:
 [[ 8  9 10 11]
 [12 13 14 15]]


# Part3

Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.


In [37]:
data = np.array([[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]])


element = data[1, 2] 
element

np.int64(15)

From the data array (from part 3 Q1), extract the first two rows and all columns.


In [39]:
subset_rows = data[:2, :]
subset_rows

array([[10, 11, 12],
       [13, 14, 15]])

From the data array (from part 3 Q1), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).


In [40]:
fancy_elements = data[[0,1,2], [1,2,1]]
fancy_elements

array([11, 15, 17])

Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.

In [41]:
scores = np.array([85, 92, 78, 65, 95, 88])
high_scores = scores[scores > 80]
high_scores

array([85, 92, 95, 88])

# Part4

Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).


In [42]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])
elementwise_multiplication = arr_op1 * arr_op2
elementwise_division = arr_op1 / arr_op2

print("Mult:\n", elementwise_multiplication)
print("Div:\n", elementwise_division)

Mult:
 [ 20  80 180]
Div:
 [5. 5. 5.]


Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.


In [44]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
total_sum = np.sum(matrix)
total_sum

np.int64(45)

From the matrix (from part 4 Q2), calculate the mean of each column.


In [46]:
column_means = np.mean(matrix, axis=0)
column_means

array([4., 5., 6.])

Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.

In [47]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10
discounted_prices = price_array * (1 - discount_percentage)
discounted_prices

array([ 90., 135., 180., 225.])