In [2]:
import numpy as np

# Part 1: Array Creation and Properties
1. Create a 1D array named arr1d with integers from 0 to 9.

In [2]:
arr1d = np.arange(0,10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 2D array named arr2d with shape (3, 3) filled with ones.

In [3]:
arr2d = np.ones((3,3))
arr2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

3. Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.

In [7]:
random_matrix = np.random.randn(3,3)
random_matrix

array([[ 0.18214388,  1.2635193 ,  0.34314998],
       [-0.78751097, -0.82748523,  1.00723272],
       [ 0.51152419, -0.62255301,  0.4180028 ]])

4. Create an array named even_numbers containing even numbers from 10 to 50 (inclusive).

In [8]:
even_numbers = np.arange(10,51,2)
even_numbers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

5. Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).

In [11]:
linspace_array = np.linspace(0,1,7)
linspace_array

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

6. Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("shape: ", arr.shape)
print("ndim: ",arr.ndim)
print("dtype: ",arr.dtype)

shape:  (2, 3)
ndim:  2
dtype:  int64


# Part 2: Array Manipulation
1. Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.

In [14]:
reshaped_arr = arr1d.reshape((2,5))
reshaped_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

2. Transpose reshaped_arr (from Q7). Name the result transposed_arr.

In [15]:
transposed_arr = reshaped_arr.T
transposed_arr

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

3. Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.

In [19]:
a = np.array([1, 2, 3])
print("a:", np.vstack(a))
b = np.array([4, 5, 6])
print()
print("b:", np.vstack(b))

a: [[1]
 [2]
 [3]]

b: [[4]
 [5]
 [6]]


4. Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.

In [21]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
arr1 = np.hstack(m1)
print("m1 = ", arr1)
arr2 = np.hstack(m2)
print("m2 = ", arr2)

m1 =  [1 2 3 4]
m2 =  [5 6 7 8]


5. Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.

In [23]:
arr_to_split = np.arange(16).reshape(4, 4)
splitted = np.hsplit(arr_to_split,2)
print(splitted[0])
print("===============")
print(splitted[1])

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


6. Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.

In [31]:
indexSplit = np.split(arr_to_split, [2] , axis=1)
for split in indexSplit:
    print(split)
    print("===========")

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Part 3: Indexing, Slicing, and Boolean Indexing
1. Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2

In [33]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(data[0,1])

11


2. From the data array (from Q13), extract the first two rows and all columns.

In [35]:
print(data[0:2,:])

[[10 11 12]
 [13 14 15]]


3. From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).

In [36]:
print(data[0,1], data[1,2], data[2,1])

11 15 17


4. Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.

In [5]:
scores = np.array([85, 92, 78, 65, 95, 88])
scores[scores > 80]

array([85, 92, 95, 88])

# Part 4: Numerical Operations and Aggregations
1. Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).

In [6]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])
print('Multiplication: ',arr_op1 * arr_op2)
print('Division: ',arr_op1 / arr_op2)

Multiplication:  [ 20  80 180]
Division:  [5. 5. 5.]


2. Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculatethe sum of all elements in the matrix.

In [7]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Sum = ", np.sum(matrix))

Sum =  45


3. From the matrix (from Q18), calculate the mean of each column.

In [10]:
print("Mean = ", np.mean(matrix,axis=0))

Mean =  [4. 5. 6.]


4. Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.

In [13]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10
print("prices after discount: ",price_array - (discount_percentage * price_array))

prices after discount:  [ 90. 135. 180. 225.]
