In [31]:
import numpy as np

In [32]:
# Add random fluctuations using normal distribution (mean=0, std=200)
sales_revenue = 1000 + np.random.normal(loc=0, scale=200, size=30)
# Assume average price per unit around 30 with variation
avg_price_per_unit = np.random.normal(loc=30, scale=2, size=30)
# Calculate base units_sold = revenue / price per unit
units_sold = sales_revenue / avg_price_per_unit
# Add noise to units sold
units_sold += np.random.normal(loc=0, scale=3, size=30)

In [33]:
avg_price_per_unit

array([25.89206301, 27.00647103, 33.34844347, 30.27996229, 33.09776691,
       31.75297404, 31.18868891, 31.17290876, 29.44224113, 28.5365184 ,
       31.54275898, 29.05694341, 30.26813011, 30.59790309, 31.55799433,
       28.88259119, 28.80582826, 31.54834026, 28.67493152, 28.48954532,
       28.98653996, 26.34786509, 30.43458195, 24.59654857, 34.35485483,
       30.45637218, 33.68395102, 29.46150984, 28.83482087, 27.56812667])

In [34]:
sales_revenue

array([ 704.46209201,  924.98982965,  811.70479595, 1112.76395513,
        859.21537138,  415.52602993, 1150.06846583, 1098.86085849,
       1064.90815235,  853.87670434,  819.44357191, 1006.81793679,
       1042.6198017 ,  791.88785649,  996.46338749,  978.45084212,
        741.47488512,  819.14865248, 1114.55214863, 1091.37267291,
       1308.1552242 , 1084.98234328, 1111.71165295,  657.45882282,
       1176.9456205 , 1113.90034849,  836.34627324, 1194.11967214,
       1092.98423951,  754.7552117 ])

In [35]:
units_sold = units_sold.round()
units_sold

array([18., 41., 25., 33., 29., 11., 35., 38., 40., 30., 28., 38., 36.,
       27., 27., 31., 26., 26., 42., 40., 43., 43., 36., 27., 33., 33.,
       30., 36., 34., 21.])

In [36]:
sales_revenue = sales_revenue.reshape(30, 1)
units_sold = units_sold.reshape(30,1)
arr1 = np.hstack((sales_revenue, units_sold))
arr1

array([[ 704.46209201,   18.        ],
       [ 924.98982965,   41.        ],
       [ 811.70479595,   25.        ],
       [1112.76395513,   33.        ],
       [ 859.21537138,   29.        ],
       [ 415.52602993,   11.        ],
       [1150.06846583,   35.        ],
       [1098.86085849,   38.        ],
       [1064.90815235,   40.        ],
       [ 853.87670434,   30.        ],
       [ 819.44357191,   28.        ],
       [1006.81793679,   38.        ],
       [1042.6198017 ,   36.        ],
       [ 791.88785649,   27.        ],
       [ 996.46338749,   27.        ],
       [ 978.45084212,   31.        ],
       [ 741.47488512,   26.        ],
       [ 819.14865248,   26.        ],
       [1114.55214863,   42.        ],
       [1091.37267291,   40.        ],
       [1308.1552242 ,   43.        ],
       [1084.98234328,   43.        ],
       [1111.71165295,   36.        ],
       [ 657.45882282,   27.        ],
       [1176.9456205 ,   33.        ],
       [1113.90034849,   

* Calculate the total sales_revenue for the month.

In [37]:
print("Total Sales Revenue = ", np.sum(arr1[:,0]))

Total Sales Revenue =  28729.967419532302


* Calculate the average units_sold per day.

In [38]:
print("Average Units Sold per Day = ", round(np.sum(arr1[:,1])/30))

Average Units Sold per Day =  32


* Determine the maximum daily sales_revenue and the day (index) it occurred.

In [39]:
print("Max Sales Revenue = ", np.max(arr1[:,0]), "Day = ", np.argmax(arr1[:,0]))

Max Sales Revenue =  1308.1552242008943 Day =  20


* Calculate the average revenue per unit sold for the entire month (total revenue / total units sold).

In [40]:
print("Average Revenue for the Month = ", np.sum(arr1[:,0]) / np.sum(arr1[:,1]))

Average Revenue for the Month =  30.020864597212437


* Identify and count how many days had sales_revenue above a certain target (e.g., $1200).

In [41]:
count = arr1[arr1[:,0] > 1200]
print("No. of days where sales_revenue > 1200: ", count.shape[0], "days")

No. of days where sales_revenue > 1200:  1 days


* Calculate the average units_sold only for days when sales_revenue was below a certain threshold (e.g., $900).

In [42]:
below = arr1[arr1[:,0] < 900]
print("Average units_sold for days when sales_revenue was below 900 = ", round(np.sum(below[:,1])/below.shape[0]))

Average units_sold for days when sales_revenue was below 900 =  25


* Assume the 30 days start on a Monday. Calculate the total sales_revenue for each of the 4 full weeks (days 1-7, 8-14, 15-21, 22-28). You will need to reshape or carefully slice your data.

In [43]:
print(f"Week1 sales = {np.sum(sales_revenue[0:7]): .2f}")
print(f"Week2 sales = {np.sum(sales_revenue[7:14]): .2f}")
print(f"Week3 sales = {np.sum(sales_revenue[14:21]): .2f}")
print(f"Week4 sales = {np.sum(sales_revenue[21:28]): .2f}")

Week1 sales =  5978.73
Week2 sales =  6678.41
Week3 sales =  7049.62
Week4 sales =  7175.46
