In [1]:
# create 1D array arr1d
arr1d = np.array([i for i in range(10)])
print("1D array (arr1d):", arr1d)


NameError: name 'np' is not defined

In [1]:
import numpy as np

In [1]:
# create 1D array arr1d
arr1d = np.array([i for i in range(10)])
print("1D array (arr1d):", arr1d)


NameError: name 'np' is not defined

In [2]:
arr1d = np.arange(10)
print("1D array (arr1d):", arr1d)

1D array (arr1d): [0 1 2 3 4 5 6 7 8 9]


In [3]:
#Step 3: Create a 2D array arr2d (3x3) filled with ones

In [4]:
arr2d = np.ones((3, 3))
print("2D array filled with ones (arr2d):\n", arr2d)


2D array filled with ones (arr2d):
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
#Create a 3x3 array random_matrix with random numbers
random_matrix = np.random.randn(3, 3)
print("Random 3x3 matrix (random_matrix):\n", random_matrix)


Random 3x3 matrix (random_matrix):
 [[-0.17432658 -0.01016921  1.54940686]
 [ 0.30338492 -0.66513383 -0.4466211 ]
 [-1.07226377 -0.5610626  -1.57481975]]


In [6]:
# create 1D array arr1d
arr1d = np.array([i for i in range(10)])
print("1D array (arr1d):", arr1d)


1D array (arr1d): [0 1 2 3 4 5 6 7 8 9]


In [7]:
#Create even_numbers from 10 to 50 (inclusive)
even_numbers = np.arange(10, 51, 2)
print("Even numbers from 10 to 50:", even_numbers)


Even numbers from 10 to 50: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [8]:
# Create linspace_array with 7 equally spaced numbers from 0 to 1
linspace_array = np.linspace(0, 1, 7)
print("7 equally spaced numbers between 0 and 1:", linspace_array)


7 equally spaced numbers between 0 and 1: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [9]:
#Analyze the array arr
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array arr:\n", arr)

print("Shape of arr:", arr.shape)
print("Number of dimensions (ndim):", arr.ndim)
print("Data type (dtype):", arr.dtype)


Array arr:
 [[1 2 3]
 [4 5 6]]
Shape of arr: (2, 3)
Number of dimensions (ndim): 2
Data type (dtype): int64


In [10]:
#Reshape arr1d into a 2x5 array
arr1d = np.arange(10)  # Recreate arr1d if not already defined
reshaped_arr = arr1d.reshape(2, 5)
print("Reshaped array (2x5):\n", reshaped_arr)


Reshaped array (2x5):
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [11]:
# Transpose reshaped_arr
transposed_arr = reshaped_arr.T  # Or use reshaped_arr.transpose()
print("Transposed array:\n", transposed_arr)


Transposed array:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [12]:
 #Stack 1D arrays vertically
python
Copy
Edit
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_vert = np.vstack((a, b))
print("Vertical stack of 1D arrays:\n", stacked_vert)

NameError: name 'python' is not defined

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_vert = np.vstack((a, b))
print("Vertical stack of 1D arrays:\n", stacked_vert)


Vertical stack of 1D arrays:
 [[1 2 3]
 [4 5 6]]


In [14]:
#Stack 2D arrays horizontally
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
stacked_horiz = np.hstack((m1, m2))
print("Horizontal stack of 2D arrays:\n", stacked_horiz)


Horizontal stack of 2D arrays:
 [[1 2 5 6]
 [3 4 7 8]]


In [15]:
# Split a 4x4 array horizontally into 2 equal parts
arr_to_split = np.arange(16).reshape(4, 4)
h_split = np.hsplit(arr_to_split, 2)
print("First half (left):\n", h_split[0])
print("Second half (right):\n", h_split[1])


First half (left):
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Second half (right):
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [16]:
#Split arr_to_split vertically at row index 2
v_split = np.vsplit(arr_to_split, 2)
print("Top half (first two rows):\n", v_split[0])
print("Bottom half (last two rows):\n", v_split[1])


Top half (first two rows):
 [[0 1 2 3]
 [4 5 6 7]]
Bottom half (last two rows):
 [[ 8  9 10 11]
 [12 13 14 15]]


In [17]:
#. Extract the element at row 1, column 2 from data
data = np.array([[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]])

element = data[1, 2]
print("Element at row 1, column 2:", element)


Element at row 1, column 2: 15


In [18]:
# Extract the first two rows and all columns
subset = data[:2, :]
print("First two rows, all columns:\n", subset)


First two rows, all columns:
 [[10 11 12]
 [13 14 15]]


In [19]:
#Extract elements 11, 15, and 17 using fancy indexing
# Row indices: [0, 1, 2]
# Col indices: [1, 2, 1]
fancy = data[[0, 1, 2], [1, 2, 1]]
print("Fancy indexed elements:", fancy)


Fancy indexed elements: [11 15 17]


In [20]:
# Use boolean indexing to find scores > 80
scores = np.array([85, 92, 78, 65, 95, 88])
high_scores = scores[scores > 80]
print("Scores greater than 80:", high_scores)


Scores greater than 80: [85 92 95 88]


In [21]:
 #Element-wise Multiplication and Division
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])

# Element-wise multiplication
multiplication = arr_op1 * arr_op2
print("Element-wise multiplication:", multiplication)

# Element-wise division
division = arr_op1 / arr_op2
print("Element-wise division:", division)


Element-wise multiplication: [ 20  80 180]
Element-wise division: [5. 5. 5.]


In [22]:
# Sum of All Elements in a 2D Matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

total_sum = np.sum(matrix)
print("Sum of all elements in the matrix:", total_sum)


Sum of all elements in the matrix: 45


In [23]:
#Mean of Each Column
column_means = np.mean(matrix, axis=0)
print("Mean of each column:", column_means)


Mean of each column: [4. 5. 6.]


In [24]:
#Apply 10% Discount Using Broadcasting
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10

discounted_prices = price_array * (1 - discount_percentage)
print("Prices after 10% discount:", discounted_prices)


Prices after 10% discount: [ 90. 135. 180. 225.]
