In [1]:
import numpy as np 

# 1. Sales Data Generation:

In [21]:
#sales_revenue
np.random.seed(42)
sales_revenue=np.random.normal(loc=1000, scale=200, size=30)
sales_revenue=np.clip(sales_revenue, 0, None)
sales_revenue

array([1099.3428306 ,  972.34713977, 1129.53770762, 1304.60597128,
        953.16932506,  953.17260861, 1315.8425631 , 1153.48694583,
        906.10512281, 1108.51200872,  907.31646144,  906.85404929,
       1048.39245431,  617.34395107,  655.0164335 ,  887.54249415,
        797.43377593, 1062.84946652,  818.3951849 ,  717.53925973,
       1293.12975378,  954.8447399 , 1013.50564094,  715.05036276,
        891.12345509, 1022.18451794,  769.80128452, 1075.13960367,
        879.87226202,  941.66125004])

In [22]:
#  units_sold
#assume average item price = 10
units_sold=(sales_revenue/10) +np.random.normal(loc=0, scale=5, size=30)
units_sold=np.clip(units_sold, 0, None)
units_sold

array([106.92575   , 106.4961049 , 112.88628464, 125.17204248,
        99.42965707,  89.21304261, 132.62857429, 105.55034396,
        83.96958204, 111.83550705,  94.42397904,  91.54224633,
       104.26100402,  60.22887663,  58.1090334 ,  85.15502837,
        77.44018374, 111.57055778,  83.55760994,  62.9387252 ,
       130.93339523,  93.55906259,  97.96595409,  74.56341772,
        94.26734312, 106.87485239,  72.78404084, 105.96789849,
        89.64354336,  99.04385064])

# 2. Combine Data:

In [23]:
combined_data=np.column_stack((sales_revenue, units_sold))
combined_data

array([[1099.3428306 ,  106.92575   ],
       [ 972.34713977,  106.4961049 ],
       [1129.53770762,  112.88628464],
       [1304.60597128,  125.17204248],
       [ 953.16932506,   99.42965707],
       [ 953.17260861,   89.21304261],
       [1315.8425631 ,  132.62857429],
       [1153.48694583,  105.55034396],
       [ 906.10512281,   83.96958204],
       [1108.51200872,  111.83550705],
       [ 907.31646144,   94.42397904],
       [ 906.85404929,   91.54224633],
       [1048.39245431,  104.26100402],
       [ 617.34395107,   60.22887663],
       [ 655.0164335 ,   58.1090334 ],
       [ 887.54249415,   85.15502837],
       [ 797.43377593,   77.44018374],
       [1062.84946652,  111.57055778],
       [ 818.3951849 ,   83.55760994],
       [ 717.53925973,   62.9387252 ],
       [1293.12975378,  130.93339523],
       [ 954.8447399 ,   93.55906259],
       [1013.50564094,   97.96595409],
       [ 715.05036276,   74.56341772],
       [ 891.12345509,   94.26734312],
       [1022.18451794,  1

In [29]:
combined_data.shape

(30, 2)

# 3. Key Performance Indicators (KPIs):

In [10]:
#Calculate the total sales_revenue for the month.
np.sum(sales_revenue)

np.float64(28871.11862489377)

In [11]:
#Calculate the average units_sold per day.
np.mean(units_sold)

np.float64(95.63124973152954)

In [15]:
#Determine the maximum daily sales_revenue and the day (index) it occurred.
print(np.max(sales_revenue))
print('day:',np.argmax(sales_revenue) + 1)

1315.8425631014784
day: 7


In [16]:
#calculate the average revenue per unit sold for the entire month (total revenue / total units sold).
avg_revenue_per_unit =  np.sum(sales_revenue)   /np.sum(units_sold)
avg_revenue_per_unit


np.float64(10.063348785376164)

# 4. Conditional Analysis:

In [17]:
# days above 1200
np.sum(sales_revenue > 1200)

np.int64(3)

In [19]:
#sales below 900
np.mean(units_sold[sales_revenue < 900])

np.float64(75.86878023084118)

# 5. Weekly Aggregations:

In [26]:
weekly= sales_revenue[:28].reshape(4, 7)


In [27]:
np.sum(weekly, axis=1) 

array([7728.01814604, 6648.01099347, 6231.90636851, 6441.64960482])