In [2]:
import numpy as np

# 1. Data Generation:

In [5]:
#Create a NumPy array for time_in_minutes from 0 to 1439 (24 hours * 60 minutes).
time_in_minutes = np.arange(0, 1440)
#print(time_in_minutes)

#Generate synthetic temperature data: a base temperature (e.g., 22°C) with some random fluctuations (use np.random.normal).
#normal(loc=mean, scale=std_dev, size=number_of_values)
temperature = np.random.normal(loc=22, scale=1.0, size=1440)
#print(temperature)

#Generate synthetic humidity data: a base humidity (e.g., 55%) with random fluctuations, ensuring values stay realistic (0-100%).
#np.clip(array, min_value, max_value)
humidity = np.random.normal(loc=55, scale=5.0, size=1440)
#np.clip(array, min_value, max_value)
humidity = np.clip(humidity, 0, 100)
#print(humidity)

#Generate synthetic pressure data: a base pressure (e.g., 1012 hPa) with random fluctuations.
pressure = np.random.normal(loc=1012, scale=2.0, size=1440)
#print(pressure)
#Combine these into a single 2D NumPy array where each row represents a minute and columns are [time, temperature, humidity, pressure].
data = np.column_stack((time_in_minutes, temperature, humidity, pressure))
print ("\n The Data : \n ",data)


 The Data : 
  [[0.00000000e+00 2.24600944e+01 5.19038776e+01 1.00949338e+03]
 [1.00000000e+00 2.30552335e+01 5.53060479e+01 1.01251642e+03]
 [2.00000000e+00 2.28772068e+01 4.29574956e+01 1.01315294e+03]
 ...
 [1.43700000e+03 1.95819239e+01 4.70673422e+01 1.01769445e+03]
 [1.43800000e+03 2.37057501e+01 5.07448837e+01 1.01081323e+03]
 [1.43900000e+03 2.16759551e+01 5.38851434e+01 1.01084900e+03]]


In [8]:
data.shape

(1440, 4)

# 2. Basic Statistics:

In [17]:
#temperature
temperature = data[:, 1] 
print(np.mean(temperature))
print(np.min(temperature))
print(np.max(temperature))
print(np.std(temperature))

22.024863835723256
18.98979406941876
25.544471392513138
1.0509371924157884


In [18]:
#humidity
humidity = data[:, 2]
print(np.mean(humidity))
print(np.max(humidity))
print(np.min(humidity))
print(np.std(humidity))

54.81191194989093
73.11373284258588
38.997570870934865
5.147217045474342


In [19]:
#pressure
pressure = data[:, 3]
print(np.mean(pressure))
print(np.max(pressure))
print(np.min(pressure))
print(np.std(pressure))

1012.0471265936109
1018.702159502783
1006.3692326733951
1.9895022431926908


# 3. Hourly Averages:

In [26]:
##temperature
temp_hourly = temperature.reshape(24, 60)
#temp_hourly[0]
print("The mean of temperature par houer \n",np.mean(temp_hourly, axis=1))

The mean of temperature par houer 
 [21.93096231 21.99853513 21.98748622 22.14257178 22.05037069 22.18045223
 22.00440998 21.77646028 22.02315129 22.04790645 21.98799288 22.09219997
 22.3467627  21.86728949 22.16579377 21.96343596 22.02698559 22.04346657
 21.81741463 21.93597148 21.9549294  22.00868242 22.19682183 22.04667901]


In [27]:
#humidity
humidity_hourly = humidity.reshape(24, 60)

print("The mean of humidity par houer \n", np.mean(humidity_hourly, axis=1))

The mean of humidity par houer 
 [54.75844752 55.53007628 55.08103282 55.05048328 54.29573355 55.06894188
 54.95446164 54.9240208  55.28543947 54.53451289 54.56958219 55.32164689
 55.34078439 54.42495825 54.24556513 54.16845885 54.17263882 55.5813175
 54.64221082 54.33853702 54.56212389 54.77675945 55.45435767 54.4037958 ]


In [28]:
#pressure
pressure_hourly = pressure.reshape(24, 60)

print("The mean of pressure par houer \n",np.mean(pressure_hourly, axis=1))

The mean of pressure par houer 
 [1011.86312403 1012.32730737 1012.14203467 1012.06408647 1012.27393678
 1011.8567981  1011.97519845 1011.9627308  1012.05255978 1012.24522164
 1011.79272873 1011.96327583 1012.05197474 1012.21223348 1012.00416135
 1011.91391452 1012.26426992 1012.14352173 1012.00487422 1011.83780447
 1011.94898125 1011.66285077 1012.39436833 1012.17308079]


# 4. Anomaly Detection (Simple):

In [32]:
temp_mask = temperature > 25
count_temp = np.sum(temp_mask)
print("tempreter is more then 25C: ",count_temp)

tempreter is more then 25C:  4


In [43]:
min_temp=np.min(temperature)

min_temp_indices = np.where(temperature == min_temp)[0]
#min_temp_indices --> 1125
#temperature[1125] -->18.9897

print("the minet",min_temp_indices)
print("the temperature",temperature[1125])

the minet [1125]
the temperature 18.98979406941876


# 5. Data Export (Optional):


In [45]:
header = "Time(min),Temperature(°C),Humidity(%),Pressure(hPa)"
# Save to CSV file
np.savetxt("smart_building_data.csv", data, delimiter=",", header=header, comments='', fmt='%.2f')
