In [27]:
import numpy as np

## 1. Sales Data Generation:

In [28]:
# Add random fluctuations using normal distribution (mean=0, std=200)
sales_revenue = 1000 + np.random.normal(loc=0, scale=200, size=30)
# Assume average price per unit around 30 with variation
avg_price_per_unit = np.random.normal(loc=30, scale=2, size=30)
# Calculate base units_sold = revenue / price per unit
units_sold = sales_revenue / avg_price_per_unit
# Add noise to units sold
units_sold += np.random.normal(loc=0, scale=3, size=30)

In [29]:
avg_price_per_unit

array([32.65056558, 28.2800733 , 30.85911256, 29.02887295, 30.81797293,
       32.32004696, 28.12774027, 28.99008368, 29.73764208, 30.68937848,
       29.10574245, 29.69711119, 29.89034787, 30.36324455, 26.30220713,
       26.65904557, 25.50062059, 32.36391289, 30.38217052, 29.59998887,
       31.9391866 , 30.20332021, 27.37131188, 27.81297136, 31.58278314,
       30.28620085, 30.40743521, 30.99773847, 31.83582931, 31.20031099])

In [30]:
sales_revenue

array([ 752.00972504, 1037.7745383 ,  709.93871792, 1097.92346907,
        744.8063196 ,  817.8079462 ,  747.46553495,  877.4006541 ,
       1188.02192544, 1003.61026098,  775.67075578, 1509.09173955,
        970.55081044, 1085.35020511, 1000.08737076, 1220.71956945,
       1034.49823017,  844.59353416, 1337.19443051,  922.89384033,
       1095.86286737, 1527.89206624,  876.52277747,  698.02008076,
        690.96290849,  823.61357493,  929.45737017,  654.20635996,
       1030.25874005,  934.37480379])

In [31]:
units_sold = units_sold.round()
units_sold

array([22., 39., 26., 33., 21., 26., 28., 31., 42., 31., 25., 50., 34.,
       35., 37., 43., 36., 26., 45., 35., 35., 47., 31., 22., 27., 31.,
       27., 17., 38., 28.])

## 2. Combine Data:

In [32]:
sales_revenue = sales_revenue.reshape(30, 1)
units_sold = units_sold.reshape(30,1)
arr1 = np.hstack((sales_revenue, units_sold))
arr1

array([[ 752.00972504,   22.        ],
       [1037.7745383 ,   39.        ],
       [ 709.93871792,   26.        ],
       [1097.92346907,   33.        ],
       [ 744.8063196 ,   21.        ],
       [ 817.8079462 ,   26.        ],
       [ 747.46553495,   28.        ],
       [ 877.4006541 ,   31.        ],
       [1188.02192544,   42.        ],
       [1003.61026098,   31.        ],
       [ 775.67075578,   25.        ],
       [1509.09173955,   50.        ],
       [ 970.55081044,   34.        ],
       [1085.35020511,   35.        ],
       [1000.08737076,   37.        ],
       [1220.71956945,   43.        ],
       [1034.49823017,   36.        ],
       [ 844.59353416,   26.        ],
       [1337.19443051,   45.        ],
       [ 922.89384033,   35.        ],
       [1095.86286737,   35.        ],
       [1527.89206624,   47.        ],
       [ 876.52277747,   31.        ],
       [ 698.02008076,   22.        ],
       [ 690.96290849,   27.        ],
       [ 823.61357493,   

## 3. Key Performance Indicators (KPIs):

* Calculate the total sales_revenue for the month.

In [33]:
print("Total Sales Revenue = ", np.sum(arr1[:,0]))

Total Sales Revenue =  28938.581127092824


* Calculate the average units_sold per day.

In [34]:
print("Average Units Sold per Day = ", round(np.sum(arr1[:,1])/30))

Average Units Sold per Day =  32


* Determine the maximum daily sales_revenue and the day (index) it occurred.

In [35]:
print("Max Sales Revenue = ", np.max(arr1[:,0]), "Day = ", np.argmax(arr1[:,0]))

Max Sales Revenue =  1527.8920662393139 Day =  21


* Calculate the average revenue per unit sold for the entire month (total revenue / total units sold).

In [36]:
print("Average Revenue for the Month = ", np.sum(arr1[:,0]) / np.sum(arr1[:,1]))

Average Revenue for the Month =  29.895228437079364


## 4. Conditional Analysis:

* Identify and count how many days had sales_revenue above a certain target (e.g., $1200).

In [37]:
count = arr1[arr1[:,0] > 1200]
print("No. of days where sales_revenue > 1200: ", count.shape[0], "days")

No. of days where sales_revenue > 1200:  4 days


* Calculate the average units_sold only for days when sales_revenue was below a certain threshold (e.g., $900).

In [38]:
below = arr1[arr1[:,0] < 900]
print("Average units_sold for days when sales_revenue was below 900 = ", round(np.sum(below[:,1])/below.shape[0]))

Average units_sold for days when sales_revenue was below 900 =  26


## 5. Weekly Aggregations:

* Assume the 30 days start on a Monday. Calculate the total sales_revenue for each of the 4 full weeks (days 1-7, 8-14, 15-21, 22-28). You will need to reshape or carefully slice your data.

In [39]:
print(f"Week1 sales = {np.sum(sales_revenue[0:7]): .2f}")
print(f"Week2 sales = {np.sum(sales_revenue[7:14]): .2f}")
print(f"Week3 sales = {np.sum(sales_revenue[14:21]): .2f}")
print(f"Week4 sales = {np.sum(sales_revenue[21:28]): .2f}")

Week1 sales =  5907.73
Week2 sales =  7409.70
Week3 sales =  7455.85
Week4 sales =  6200.68
