In [5]:
import numpy as np

arr1d = np.arange(10)
print("arr1d:", arr1d)

arr1d: [0 1 2 3 4 5 6 7 8 9]


#Part 1: Array Creation and Properties

In [6]:
arr2d = np.ones((3, 3))
print("arr2d:\n", arr2d)

arr2d:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
random_matrix = np.random.randn(3, 3)
print("random_matrix:\n", random_matrix)

random_matrix:
 [[-0.72399839 -2.23660685  0.46245371]
 [ 0.44036526 -0.60210651 -0.08529459]
 [ 0.77856531  0.646151    0.51678057]]


In [9]:
even_numbers = np.arange(10, 51, 2)
print("even_numbers:", even_numbers)

even_numbers: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [15]:
linspace_array = np.linspace(0, 1, 7)
print("linspace_array:\n", linspace_array)

linspace_array:
 [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)
print("Dimensions (ndim):", arr.ndim)
print("Data type (dtype):", arr.dtype)

Shape: (2, 3)
Dimensions (ndim): 2
Data type (dtype): int64


#Part 2: Array Manipulation

In [17]:
reshaped_arr = arr1d.reshape(2, 5)
print("reshaped_arr:\n", reshaped_arr)

reshaped_arr:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [18]:
transposed_arr = reshaped_arr.T
print("transposed_arr:\n", transposed_arr)

transposed_arr:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_vertically = np.vstack((a, b))
print("Stacked Vertically:\n", stacked_vertically)

Stacked Vertically:
 [[1 2 3]
 [4 5 6]]


In [20]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
stacked_horizontally = np.hstack((m1, m2))
print("Stacked Horizontally:\n", stacked_horizontally)

Stacked Horizontally:
 [[1 2 5 6]
 [3 4 7 8]]


In [21]:
arr_to_split = np.arange(16).reshape(4, 4)
split_horizontally = np.hsplit(arr_to_split, 2)
print("Split Horizontally (2 parts):")
for i, part in enumerate(split_horizontally, start=1):
    print(f"Part {i}:\n", part)

Split Horizontally (2 parts):
Part 1:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Part 2:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [22]:
split_vertically = np.vsplit(arr_to_split, [2])
print("Split Vertically (at index 2):")
for i, part in enumerate(split_vertically, start=1):
    print(f"Part {i}:\n", part)

Split Vertically (at index 2):
Part 1:
 [[0 1 2 3]
 [4 5 6 7]]
Part 2:
 [[ 8  9 10 11]
 [12 13 14 15]]


Part 3: Indexing, Slicing, and Boolean Indexing

In [23]:
data = np.array([[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]])

element = data[1, 2]
print("Element at row 1, column 2:", element)

Element at row 1, column 2: 15


In [24]:
first_two_rows = data[:2, :]
print("First two rows:\n", first_two_rows)

First two rows:
 [[10 11 12]
 [13 14 15]]


In [25]:
fancy_elements = data[[0, 1, 2], [1, 2, 1]]  # data[0,1], data[1,2], data[2,1]
print("Fancy indexed elements:", fancy_elements)

Fancy indexed elements: [11 15 17]


In [26]:
scores = np.array([85, 92, 78, 65, 95, 88])
high_scores = scores[scores > 80]
print("Scores greater than 80:", high_scores)

Scores greater than 80: [85 92 95 88]


Part 4: Numerical Operations and Aggregations

In [27]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])

multiplication = arr_op1 * arr_op2
division = arr_op1 / arr_op2

print("Element-wise multiplication:", multiplication)
print("Element-wise division:", division)

Element-wise multiplication: [ 20  80 180]
Element-wise division: [5. 5. 5.]


In [28]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

total_sum = matrix.sum()
print("Sum of all elements:", total_sum)

Sum of all elements: 45


In [29]:
column_means = matrix.mean(axis=0)
print("Mean of each column:", column_means)

Mean of each column: [4. 5. 6.]


In [30]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10

discounted_prices = price_array * (1 - discount_percentage)
print("Discounted prices:", discounted_prices)

Discounted prices: [ 90. 135. 180. 225.]
