In [3]:
import numpy as np

### Part 1: Array Creation and Properties

1.Create a 1D array named arr1d with integers from 0 to 9

In [6]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2.Create a 2D array named arr2d with shape (3, 3) filled with ones

In [7]:
arr2 = np.ones((3,3))
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

3.Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution

In [8]:
random_matrix = np.random.randn(3, 3) 
random_matrix

array([[ 1.5285445 ,  2.13066638,  0.23984521],
       [ 0.42034054,  0.32575194,  0.15496106],
       [ 3.22657572, -0.15239874,  0.25380351]])

4.Create an array named even_numbers containing even numbers from 10 to 50 (inclusive)

In [9]:
even_numbers = np.arange(10, 52, 2) 
even_numbers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

5.Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive)

In [12]:
linspace_array = np.linspace(0 , 1, 7)
linspace_array

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

6- Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Data type:", arr.dtype)

Shape: (2, 3)
Dimensions: 2
Data type: int64


### Part 2: Array Manipulation 

1.Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr 

In [14]:
reshaped_arr = arr1.reshape(2, 5) 
reshaped_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

2.Transpose reshaped_arr (from Q7). Name the result transposed_arr 

In [16]:
transposed_arr = reshaped_arr.T
transposed_arr

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

3.Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically

In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
vertical_stack = np.vstack((a, b))
vertical_stack 

array([[1, 2, 3],
       [4, 5, 6]])

4.Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally

In [19]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]]) 
horizontal_stack = np.hstack ((m1,m2))
horizontal_stack 

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

5.Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts

In [20]:
arr_to_split = np.arange(16).reshape(4, 4) 
h_split1, h_split2 = np.hsplit(arr_to_split, 2) 
h_split1
h_split2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

6.Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts

In [21]:
v_split1, v_split2 = np.vsplit(arr_to_split, [2])
v_split1
v_split2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Part 3: Indexing, Slicing, and Boolean Indexing

1.Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2 

In [27]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]) 
element = data[1, 2]
print("Element at at row 1, column 2:", element) 

Element at at row 1, column 2: 15


2.From the data array (from Q13), extract the first two rows and all columns

In [28]:
first_two_rows = data[:2, :]
print("First two rows:\n", first_two_rows) 

First two rows:
 [[10 11 12]
 [13 14 15]]


3.From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns)

In [31]:
rows = [0, 1, 2]
cols = [1, 2, 1]
selected_elements = data[rows, cols] 
print("Selected_elements:", selected_elements) 

Selected_elements: [11 15 17]


4.Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80 

In [32]:
scores = np.array([85, 92, 78, 65, 95, 88]) 
high_scores = scores[scores > 80]
print("Scores > 80:", high_scores) 

Scores > 80: [85 92 95 88]


### Part 4: Numerical Operations and Aggregations

1.Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2)

In [33]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])
multiplication = arr_op1 * arr_op2
division = arr_op1 / arr_op2
print("Multiplication: ", multiplication)
print("Division: ",division) 

Multiplication:  [ 20  80 180]
Division:  [5. 5. 5.]


2.Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculatethe sum of all elements in the matrix

In [34]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
total_sum = np.sum(matrix)
print("Sum of all elements:", total_sum) 

Sum of all elements: 45


3.From the matrix (from Q18), calculate the mean of each column

In [35]:
column_means = matrix.mean(axis=0)
print("Mean of each column:", column_means)

Mean of each column: [4. 5. 6.]


4.Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting

In [36]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10
discounted_prices = price_array * (1 - discount_percentage)
print("Discounted prices:",discounted_prices)

Discounted prices: [ 90. 135. 180. 225.]
