In [1]:
import numpy as np 

In [3]:
time_in_minutes = np.arange(1440) 
print("Time in minutes:", time_in_minutes[:10]) 

Time in minutes: [0 1 2 3 4 5 6 7 8 9]


In [4]:
temperature = 22 + np.random.normal(0, 1, 1440) 
print("Sample temperature values:", temperature[:10]) 

Sample temperature values: [22.33810917 23.62383791 22.97972412 20.97466157 21.63872265 22.46476225
 20.88148294 24.63626089 21.13413827 20.04339284]


In [5]:
humidity = 55 + np.random.normal(0, 5, 1440)
humidity = np.clip(humidity, 0, 100)
print("Sample humidity values:", humidity[:10]) 

Sample humidity values: [51.53686205 55.1193091  60.1968947  55.17395187 53.01765042 55.50748053
 62.95446162 61.76264727 53.68535229 48.41365794]


In [7]:
pressure = 1012 + np.random.normal(0, 3, 1440)
print("Sample pressure values:", pressure[:10]) 

Sample pressure values: [1009.6380258  1010.47199437 1010.29860044 1008.60830985 1012.72157663
 1013.32999398 1012.07791145 1010.93940982 1010.68289222 1015.54935235]


In [8]:
data = np.column_stack((time_in_minutes, temperature, humidity, pressure))
print("First 5 rows of data:\n", data[:5]) 

First 5 rows of data:
 [[0.00000000e+00 2.23381092e+01 5.15368620e+01 1.00963803e+03]
 [1.00000000e+00 2.36238379e+01 5.51193091e+01 1.01047199e+03]
 [2.00000000e+00 2.29797241e+01 6.01968947e+01 1.01029860e+03]
 [3.00000000e+00 2.09746616e+01 5.51739519e+01 1.00860831e+03]
 [4.00000000e+00 2.16387227e+01 5.30176504e+01 1.01272158e+03]]


In [9]:
print("Average temperature:", np.mean(temperature))
print("Minimum temperature:", np.min(temperature))
print("Maximum temperature:", np.max(temperature)) 

Average temperature: 21.988615670001785
Minimum temperature: 19.028958766113412
Maximum temperature: 25.278079910257727


In [10]:
print("Average humidity:", np.mean(humidity))
print("Minimum humidity:", np.min(humidity))
print("Maximum humidity:", np.max(humidity))

Average humidity: 54.93449092293407
Minimum humidity: 37.34204334331719
Maximum humidity: 71.36097015396867


In [11]:
print("Average pressure:", np.mean(pressure))
print("Minimum pressure:", np.min(pressure))
print("Maximum pressure:", np.max(pressure)) 

Average pressure: 1011.9755564796963
Minimum pressure: 1001.0483096306097
Maximum pressure: 1021.7349809229619


In [12]:
print("Standard deviation of temperature:", np.std(temperature)) 

Standard deviation of temperature: 0.9988694964508195


In [13]:
print("Standard deviation of humidity:", np.std(humidity)) 

Standard deviation of humidity: 4.904618382183718


In [14]:
print("Standard deviation of pressure:", np.std(pressure))

Standard deviation of pressure: 3.004756470247035


In [16]:
temperature_hourly = temperature.reshape(24, 60).mean(axis=1) 
print("Hourly average temperature:\n", temperature_hourly) 

Hourly average temperature:
 [21.94203377 21.94590536 22.00373289 21.99834855 22.0992877  21.92084876
 22.04932102 22.00775046 21.98958804 22.01248604 22.11570881 21.79073156
 22.14013463 21.71822889 22.21381399 21.91933472 21.93364424 21.93352383
 22.00305096 21.89389841 21.92250598 22.14538507 22.0141024  22.01340998]


In [17]:
humidity_hourly = humidity.reshape(24, 60).mean(axis=1) 
print("\nHourly average humidity:\n", humidity_hourly) 


Hourly average humidity:
 [56.34271597 54.14927071 54.95934465 55.25013064 55.03899517 54.89757188
 54.65450837 54.87961006 54.56897826 55.50885604 55.38075774 54.83345213
 55.72056035 55.02889059 54.53278023 54.77042315 54.05657794 55.64613471
 54.56102734 54.68419944 54.38506729 55.34443099 53.9157296  55.31776889]


In [19]:
pressure_hourly = pressure.reshape(24, 60).mean(axis=1)
print("\nHourly average pressure:\n", pressure_hourly)


Hourly average pressure:
 [1011.80950436 1012.53320526 1011.84673253 1011.78451718 1011.55089306
 1012.01103353 1011.25326009 1012.45701931 1011.80980827 1012.74233504
 1012.1426146  1010.93056328 1011.96298236 1012.7212321  1012.04228617
 1011.92324199 1012.32761988 1011.70828274 1012.33961503 1011.93271228
 1012.24196067 1011.10169255 1012.23137934 1012.00886389]


In [20]:
high_temp_count = np.sum(temperature > 25)
print("Number of minutes where temperature > 25°C:", high_temp_count) 

Number of minutes where temperature > 25°C: 2


In [21]:
min_temp_time = time_in_minutes[np.argmin(temperature)]
print("Minimum temperature occurred at minute:", min_temp_time) 

Minimum temperature occurred at minute: 1137


In [22]:
np.savetxt("environment_data.csv", data, delimiter=",", header="Time,Temperature,Humidity,Pressure", comments='', fmt="%.2f")
print("Data saved to 'environment_data.csv'")

Data saved to 'environment_data.csv'
