In [13]:
import numpy as np

1.Create a 1D array named arr1d with integers from 0 to 9

# PART 1 : Array Creation and Properties

In [3]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2.Create a 2D array named arr2d with shape (3, 3) filled with ones

In [4]:
arr2d = np.ones(9)
print(arr2d)

[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
arr2d.reshape(3,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

3. Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.

In [6]:
random_matrix = np.random.randn(3, 3)
print(random_matrix)

[[ 0.21380138 -1.6192938   0.13576963]
 [-0.94378921  0.35686222  1.90829921]
 [ 0.05153518 -0.20626973  0.09066609]]


4. Create an array named even_numbers containing even numbers from 10 to 50 (inclusive)

In [7]:
even_numbers = np.arange(10, 51, 2)
print(even_numbers)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


5. Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).

In [8]:
linspace_array = np.linspace(0, 1, 7)
print(linspace_array)

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


6. Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Data type:", arr.dtype)

Shape: (2, 3)
Dimensions: 2
Data type: int64


# PART 2 : Array Manipulation

1. Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.

In [10]:
reshaped_arr = arr1d.reshape(2, 5)
reshaped_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

2. Transpose reshaped_arr (from part 2 Q1). Name the result transposed_arr.

In [11]:
transposed_arr = reshaped_arr.T
transposed_arr

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

3. Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.

In [28]:
a = np.array([1,2,3])
b = np.array([4,5,6])

vertical_stacking = np.stack((a, b), axis = 0)
vertical_stacking


array([[1, 2, 3],
       [4, 5, 6]])

4. Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.

In [43]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

horizental_stack = np.hstack((m1,m2))
print(horizental_stack)


[[1 2 5 6]
 [3 4 7 8]]


5. Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.

In [ ]:
arr_to_split = np.arange(16).reshape(4,4)

part1, part2 = np.hsplit(arr_to_split, 2)

print("part 1:\n" , part1)
print("Part 2:\n", part2)

Part 1:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Part 2:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


6. Split the array arr_to_split (from part 2 Q5 ) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.

In [46]:
top_part, bottom_part = np.vsplit(arr_to_split, [2])

print("Top part:\n", top_part)
print("Bottom part:\n", bottom_part)

Top part:
 [[0 1 2 3]
 [4 5 6 7]]
Bottom part:
 [[ 8  9 10 11]
 [12 13 14 15]]


# PART 3 : Indexing, Slicing, and Boolean Indexing

1. Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.

In [47]:
data = np.array([[10, 11, 12], 
                 [13, 14, 15], 
                 [16, 17, 18]])

element = data[1, 2]
print("Element at row 1, column 2:", element)

Element at row 1, column 2: 15


2. From the data array (from part 3 Q1), extract the first two rows and all columns.

In [48]:
element = data[:2,:]
element

array([[10, 11, 12],
       [13, 14, 15]])

3. From the data array (from part 3 Q1), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).

In [50]:

rows = [0, 1, 2]
cols = [1, 2, 1]

elements = data[rows, cols]
print("Selected elements:", elements)

Selected elements: [11 15 17]


4. Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.

In [52]:
scores = np.array([85, 92, 78, 65, 95, 88])


high_scores = scores[scores > 80]
print("Scores greater than 80:", high_scores)

Scores greater than 80: [85 92 95 88]


# PART 4 : Numerical Operations and Aggregations

1. Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).

In [54]:
arr_op1 = np.array([10,20,30])
arr_op2 = np.array([2,4,6])

multi = arr_op1 * arr_op2
dev = arr_op1 / arr_op2
print("Multiplication",multi)
print("divition", dev)

Multiplication [ 20  80 180]
divition [5. 5. 5.]


2. Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.

In [57]:
matrix = np.array([1,2,3]),[4,5,6],[7,8,9]
total = np.sum(matrix)
print(total)

45


3. From the matrix (from part 4 Q2), calculate the mean of each column.

In [61]:
mean1 = np.mean(matrix , axis= 0)
print(mean1)

[4. 5. 6.]


4. Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.

In [62]:
price_array = np.array([100,150,200,250])
discount_percentage = 0.10

price_after_discount = price_array * (1 - discount_percentage)
print(price_after_discount)

[ 90. 135. 180. 225.]
