In [2]:
import numpy as np

In [2]:
# Part 1: Array Creation and Properties

In [3]:
# 1. Create a 1D array named arr1d with integers from 0 to 9.
arr1d = np.arange(10)
print("1D array:", arr1d)

1D array: [0 1 2 3 4 5 6 7 8 9]


In [7]:
# 2. Create a 2D array named arr2d with shape (3, 3) filled with ones. 
arr2d = np.ones ((3,3))
print("2D array: \n", arr2d)

2D array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
# 3. Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.
random_matrix = np.random.randn(3, 3)
print("3x3 array: \n",random_matrix ) 

3x3 array: 
 [[-1.01671936  0.41232577  2.46714391]
 [-0.96087737 -0.62143034  0.81780207]
 [ 0.24087094 -0.46937424  0.2898255 ]]


In [9]:
# 4. Create an array named even_numbers containing even numbers from 10 to 50 (inclusive).
even_numbers= np.arange(10, 51, 2)
print("even numbers from 10 to 50: \n", even_numbers)

even numbers from 10 to 50: 
 [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [10]:
# 5. Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).
linspace_array= np.linspace(0,1,7)
print("7 equally spaced numbers: \n", linspace_array)

7 equally spaced numbers: 
 [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [12]:
# 6. Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("shape: ", arr.shape)
print("ndim: ", arr.ndim)
print("dtype: ", arr.dtype)

shape:  (2, 3)
ndim:  2
dtype:  int64


In [13]:
# Part 2: Array Manipulation

In [16]:
# 1. Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.
arr1d= np.arange(10)
reshaped_arr= arr1d.reshape(2,5)
print("2x5 2D array: \n", reshaped_arr)

2x5 2D array: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
# 2. Transpose reshaped_arr (from part 2 Q1). Name the result transposed_arr.
arr1d= np.arange(10)
reshaped_arr= arr1d.reshape(2,5)
transposed_arr= reshaped_arr.T
print("Transpose array: \n", transposed_arr)

Transpose array: 
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [20]:
# 3. Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked= np.vstack((a, b))
print("Vertically stacked array: \n", stacked)

Vertically stacked array: 
 [[1 2 3]
 [4 5 6]]


In [19]:
# 4. Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.
m1 = np.array([[1, 2], [3, 4]]) 
m2 = np.array([[5, 6], [7, 8]])
stacked= np.hstack((m1, m2))
print("Horizontally stacked array:\n", stacked)

Horizontally stacked array:
 [[1 2 5 6]
 [3 4 7 8]]


In [21]:
# 5. Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.
arr_to_split = np.arange(16).reshape(4, 4)
left_part= np.hsplit(arr_to_split, 2)
right_part= np.hsplit(arr_to_split, 2)
print("Left part:\n", left_part)
print("Right part:\n", right_part)

Left part:
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
Right part:
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [22]:
# 6. Split the array arr_to_split (from part 2 Q5 ) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.
arr_to_split = np.arange(16).reshape(4, 4)
top_part = np.vsplit(arr_to_split, [2])
bottom_part = np.vsplit(arr_to_split, [2])
print("Top part:\n", top_part)
print("Bottom part:\n", bottom_part)

Top part:
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
Bottom part:
 [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [23]:
# Part 3: Indexing, Slicing, and Boolean Indexing

In [24]:
# 1. Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
element = data[1, 2]
print("element at row 1, column 2: ", element)

element at row 1, column 2:  15


In [25]:
# 2. From the data array (from part 3 Q1), extract the first two rows and all columns.
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
extracted_data= data[:2, :]
print("the first two rows and all columns: \n", extracted_data)

the first two rows and all columns: 
 [[10 11 12]
 [13 14 15]]


In [26]:
# 3. From the data array (from part 3 Q1), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
rows = [0, 1, 2]
cols = [1, 2, 1]
extracted_elements = data[rows, cols]
print("Extracted elements using fancy indexing:", extracted_elements)

Extracted elements using fancy indexing: [11 15 17]


In [27]:
# 4. Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.
scores = np.array([85, 92, 78, 65, 95, 88])
high_scores = scores[scores > 80]
print("Scores greater than 80:", high_scores)

Scores greater than 80: [85 92 95 88]


In [28]:
# Part 4: Numerical Operations and Aggregations

In [29]:
# 1. Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])
mul_result = arr_op1 * arr_op2
div_result = arr_op1 / arr_op2
print("Element-wise multiplication:", mul_result)
print("Element-wise division:", div_result)

Element-wise multiplication: [ 20  80 180]
Element-wise division: [5. 5. 5.]


In [3]:
# 2. Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sum = matrix.sum()
print("Sum of all elements in the matrix:", sum)

Sum of all elements in the matrix: 45


In [4]:
# 3. From the matrix (from part 4 Q2), calculate the mean of each column.
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
column_means = matrix.mean(axis=0)
print("Mean of each column:", column_means)

Mean of each column: [4. 5. 6.]


In [6]:
# 4. Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10
discounted_prices = price_array * (1 - discount_percentage)
print("Discounted prices:", discounted_prices)

Discounted prices: [ 90. 135. 180. 225.]
