In [1]:
import numpy as np

Create a 1D array named arr1d with integers from 0 to 9.

In [2]:
arr1d = np.arange(10)
print("arr1d:", arr1d)

arr1d: [0 1 2 3 4 5 6 7 8 9]


Create a 2D array named arr2d with shape (3, 3) filled with ones.

In [3]:
arr2d = np.ones((3, 3))
print("arr2d:\n", arr2d)

arr2d:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.

In [9]:
random_matrix = np.random.randn(3, 3)
print("random_matrix:\n", random_matrix)

random_matrix:
 [[-1.32972985  0.88575682 -0.01787568]
 [ 0.92158756 -0.9908581  -0.33768149]
 [ 1.21887354  0.07919373  0.9179337 ]]


Create an array named even_numbers containing even numbers from 10 to 50 (inclusive).

In [5]:
even_numbers = np.arange(10, 51, 2)
print("even_numbers:", even_numbers)

even_numbers: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).

In [6]:
linspace_array = np.linspace(0, 1, 7)
print("linspace_array:", linspace_array)

linspace_array: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)
print("Number of dimensions (ndim):", arr.ndim)
print("Data type (dtype):", arr.dtype)

Shape: (2, 3)
Number of dimensions (ndim): 2
Data type (dtype): int64


# part2 

Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.

In [10]:
arr1d = np.arange(10)
reshaped_arr = arr1d.reshape(2, 5)
print("reshaped_arr:\n", reshaped_arr)

reshaped_arr:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


Transpose reshaped_arr (from part 2 Q1). Name the result transposed_arr.

In [11]:
transposed_arr = reshaped_arr.T
print("transposed_arr:\n", transposed_arr)

transposed_arr:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

stacked_vertically = np.vstack((a, b))
print("stacked_vertically:\n", stacked_vertically)

stacked_vertically:
 [[1 2 3]
 [4 5 6]]


Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.

In [13]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

stacked_horizontally = np.hstack((m1, m2))
print("stacked_horizontally:\n", stacked_horizontally)

stacked_horizontally:
 [[1 2 5 6]
 [3 4 7 8]]


Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.

In [14]:
arr_to_split = np.arange(16).reshape(4, 4)
print("arr_to_split:\n", arr_to_split)

split_horizontal = np.hsplit(arr_to_split, 2)
print("Horizontal Split - Part 1:\n", split_horizontal[0])
print("Horizontal Split - Part 2:\n", split_horizontal[1])

arr_to_split:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Horizontal Split - Part 1:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Horizontal Split - Part 2:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Split the array arr_to_split (from part 2 Q5 ) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.

In [15]:
split_vertical = np.vsplit(arr_to_split, 2)
print("Vertical Split - Part 1:\n", split_vertical[0])
print("Vertical Split - Part 2:\n", split_vertical[1])

Vertical Split - Part 1:
 [[0 1 2 3]
 [4 5 6 7]]
Vertical Split - Part 2:
 [[ 8  9 10 11]
 [12 13 14 15]]


# Part 3

Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.

In [18]:
data = np.array([[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]])

element = data[1, 2]
print("Element at row 1, column 2:", element)


Element at row 1, column 2: 15


From data, extract the first two rows and all columns.

In [19]:
first_two_rows = data[0:2, :]
print("First two rows:\n", first_two_rows)


First two rows:
 [[10 11 12]
 [13 14 15]]


From data, extract the elements 11, 15, and 17 using fancy indexing.

In [20]:
rows = np.array([0, 1, 2])
cols = np.array([1, 2, 1])

fancy_selected = data[rows, cols]
print("Elements 11, 15, 17:", fancy_selected)


Elements 11, 15, 17: [11 15 17]


 Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.

In [21]:
scores = np.array([85, 92, 78, 65, 95, 88])

greater_than_80 = scores[scores > 80]
print("Scores greater than 80:", greater_than_80)


Scores greater than 80: [85 92 95 88]


# part 4

 Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).

In [23]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])

# Element-wise multiplication
multiplication_result = arr_op1 * arr_op2
print("Element-wise multiplication:", multiplication_result)

# Element-wise division
division_result = arr_op1 / arr_op2
print("Element-wise division:", division_result)


Element-wise multiplication: [ 20  80 180]
Element-wise division: [5. 5. 5.]


Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.

In [24]:
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

total_sum = matrix.sum()
print("Sum of all elements:", total_sum)


Sum of all elements: 45


From the matrix (from part 4 Q2), calculate the mean of each column

In [25]:
column_means = matrix.mean(axis=0)
print("Mean of each column:", column_means)


Mean of each column: [4. 5. 6.]


Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.


In [26]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10

discounted_prices = price_array * (1 - discount_percentage)
print("Discounted prices:", discounted_prices)


Discounted prices: [ 90. 135. 180. 225.]
