In [2]:
# Part 1: Array Creation and Properties

In [7]:
## 1. Create a 1D array named arr1d with integers from 0 to 9 

!pip install numpy
import numpy as np

arr1d = np.array([0,1,2,3,4,5,6,7,8,9])
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
## 2. Creat a 2D array named arr2d with shape (3,3) filled with ones

import numpy as np

arr2d = np.ones((3,3))
arr2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
## 3. Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.

random_matrix = np.random.rand(3,3)
random_matrix

array([[0.55124724, 0.66297851, 0.00577092],
       [0.36983964, 0.34713614, 0.20227634],
       [0.18427641, 0.41033748, 0.6860457 ]])

In [10]:
## 4. Create an array named even_numbers containing even numbers from 10 to 50 (inclusive).

even_number = np.arange(10,51,2)
even_number

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [14]:
## 5. Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).

linspace_array = np.linspace(0,1,7)
linspace_array

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [17]:
## 6. Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Data type:", arr.dtype)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Data type: int64


In [18]:
# Part 2: Array Manipulation

In [19]:
## 1. Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.

reshaped_arr = arr1d.reshape(2, 5)
reshaped_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
## 2. Transpose reshaped_arr (from part 2 Q1). Name the result transposed_arr.

transposed_arr = reshaped_arr.T 
transposed_arr

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [21]:
## 3. Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

v_stacked = np.vstack((a, b)) 
v_stacked

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
## 4. Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.

m1 = np.array([[1, 2],
               [3, 4]])
m2 = np.array([[5, 6],
               [7, 8]])

h_stack = np.hstack((m1, m2))
h_stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [27]:
## 5. Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.

arr_to_split = np.arange(16).reshape(4, 4)
print("Original 4×4 array:\n", arr_to_split)

left_half, right_half = np.hsplit(arr_to_split, 2) 
left_half, right_half

Original 4×4 array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

In [30]:
## 6. Split the array arr_to_split (from part 2 Q5 ) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.

top_half, bottom_half = np.vsplit(arr_to_split, [2])
print("Top half (2×4):\n", top_half)
print("\nBottom half (2×4):\n", bottom_half)

Top half (2×4):
 [[0 1 2 3]
 [4 5 6 7]]

Bottom half (2×4):
 [[ 8  9 10 11]
 [12 13 14 15]]


In [31]:
# Part 3: Indexing, Slicing, and Boolean Indexing

In [32]:
## 1. Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.

data = np.array([[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]])

element = data[1, 2]
element

np.int64(15)

In [33]:
## 2. From the data array (from part 3 Q1), extract the first two rows and all columns.

subset = data[0:2, :] 
subset

array([[10, 11, 12],
       [13, 14, 15]])

In [34]:
## 3. From the data array (from part 3 Q1), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).

fancy_elements = data[[0, 1, 2], [1, 2, 1]]
fancy_elements

array([11, 15, 17])

In [35]:
## 4. Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.

scores = np.array([85, 92, 78, 65, 95, 88])
high_scores = scores[scores > 80]
high_scores

array([85, 92, 95, 88])

In [36]:
# Part 4: Numerical Operations and Aggregations

In [38]:
## 1. Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).

arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])

multiplication = arr_op1 * arr_op2
division = arr_op1 / arr_op2

print("Element-wise multiplication:", multiplication)
print("Element-wise division:", division)

Element-wise multiplication: [ 20  80 180]
Element-wise division: [5. 5. 5.]


In [39]:
## 2. Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

total_sum = np.sum(matrix)
total_sum

np.int64(45)

In [40]:
## 3. From the matrix (from part 4 Q2), calculate the mean of each column.

column_means = np.mean(matrix, axis=0)
column_means

array([4., 5., 6.])

In [41]:
## 4. Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.

price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10

discounted_prices = price_array * (1 - discount_percentage)
discounted_prices

array([ 90., 135., 180., 225.])