In [27]:
import numpy as np

In [28]:
time_in_minutes = np.arange(1440)
print(time_in_minutes)

[   0    1    2 ... 1437 1438 1439]


In [29]:
temp = np.random.normal(22,5,size=1440)
temp = temp.astype(int)
print(temp)

[24 30 27 ... 17 22 23]


In [30]:
humidity = np.random.normal(50,10,size=1440)
humidity = humidity.astype(int)
print(humidity)

[48 44 61 ... 54 65 65]


In [31]:
pressure = np.random.normal(1012,10,size=1440)
pressure = pressure.astype(int)
print(pressure)

[1030  999 1007 ... 1019 1020 1025]


In [32]:
data = np.column_stack((time_in_minutes,temp,humidity,pressure))
print(data)

[[   0   24   48 1030]
 [   1   30   44  999]
 [   2   27   61 1007]
 ...
 [1437   17   54 1019]
 [1438   22   65 1020]
 [1439   23   65 1025]]


In [33]:
avg_temp = np.mean(temp)
print (f"Average Temperature: {avg_temp:.2f}°C")
avg_humidity = np.mean(humidity)
print (f"average Humidity: {avg_humidity:.2f}%")
avg_pressure = np.mean(pressure)
print (f"Average Pressure: {avg_pressure:.2f}hPa")

Average Temperature: 21.48°C
average Humidity: 49.68%
Average Pressure: 1011.75hPa


In [34]:
min_temp = np.min(temp)
print(f"minimum Temperature: {min_temp}°C")
min_humidity = np.min(humidity)
print(f"minimum Humidity: {min_humidity}%")
min_pressure = np.min(pressure)
print(f"minimum Pressure: {min_pressure}hPa")

minimum Temperature: 7°C
minimum Humidity: 17%
minimum Pressure: 980hPa


In [35]:
max_temp = np.max(temp)
print(f"maximum Temperature: {max_temp}°C")
max_humidity = np.max(humidity)
print(f"maximum Humidity: {max_humidity}%")
max_pressure = np.max(pressure)
print(f"maximum Pressure: {max_pressure}hPa")

maximum Temperature: 39°C
maximum Humidity: 81%
maximum Pressure: 1046hPa


In [36]:
std_temp = np.std(temp)
print(f"Standard Deviation of Temperature: {std_temp:.2f}°C")
std_humidity = np.std(humidity)
print(f"Standard Deviation of Humidity: {std_humidity:.2f}%")
std_pressure = np.std(pressure)
print(f"Standard Deviation of Pressure: {std_pressure:.2f}hPa")

Standard Deviation of Temperature: 4.95°C
Standard Deviation of Humidity: 10.03%
Standard Deviation of Pressure: 9.90hPa


In [37]:
for hour in range(24):
    hour_count = hour + 1
    start_index = hour * 60
    end_index = start_index + 60
    avg_hour_tempreture = np.mean(temp[start_index:end_index])
    print(f"Average Temperature for hour {hour_count}: {avg_hour_tempreture:.2f}°C")

Average Temperature for hour 1: 21.92°C
Average Temperature for hour 2: 21.85°C
Average Temperature for hour 3: 21.37°C
Average Temperature for hour 4: 20.72°C
Average Temperature for hour 5: 21.98°C
Average Temperature for hour 6: 21.72°C
Average Temperature for hour 7: 22.10°C
Average Temperature for hour 8: 22.62°C
Average Temperature for hour 9: 21.05°C
Average Temperature for hour 10: 22.38°C
Average Temperature for hour 11: 21.07°C
Average Temperature for hour 12: 21.57°C
Average Temperature for hour 13: 22.53°C
Average Temperature for hour 14: 21.30°C
Average Temperature for hour 15: 20.50°C
Average Temperature for hour 16: 20.80°C
Average Temperature for hour 17: 21.20°C
Average Temperature for hour 18: 21.50°C
Average Temperature for hour 19: 21.12°C
Average Temperature for hour 20: 22.12°C
Average Temperature for hour 21: 20.55°C
Average Temperature for hour 22: 21.18°C
Average Temperature for hour 23: 20.95°C
Average Temperature for hour 24: 21.45°C


In [38]:
for hour in range(24):
    hour_count = hour + 1
    start_index = hour * 60
    end_index = start_index + 60
    avg_hour_humidity = np.mean(humidity[start_index:end_index])
    print(f"Average Humidity for hour {hour_count}: {avg_hour_humidity:.2f}%")

Average Humidity for hour 1: 48.95%
Average Humidity for hour 2: 48.50%
Average Humidity for hour 3: 50.25%
Average Humidity for hour 4: 49.72%
Average Humidity for hour 5: 49.82%
Average Humidity for hour 6: 51.13%
Average Humidity for hour 7: 50.23%
Average Humidity for hour 8: 49.53%
Average Humidity for hour 9: 50.72%
Average Humidity for hour 10: 47.15%
Average Humidity for hour 11: 50.32%
Average Humidity for hour 12: 46.77%
Average Humidity for hour 13: 50.30%
Average Humidity for hour 14: 50.48%
Average Humidity for hour 15: 51.47%
Average Humidity for hour 16: 48.55%
Average Humidity for hour 17: 49.38%
Average Humidity for hour 18: 47.52%
Average Humidity for hour 19: 50.98%
Average Humidity for hour 20: 47.25%
Average Humidity for hour 21: 49.83%
Average Humidity for hour 22: 51.50%
Average Humidity for hour 23: 51.33%
Average Humidity for hour 24: 50.72%


In [39]:
for hour in range(24):
    hour_count = hour + 1
    start_index = hour * 60
    end_index = start_index + 60
    avg_hour_pressure = np.mean(pressure[start_index:end_index])
    print(f"Average Pressure for hour {hour_count}: {avg_hour_pressure:.2f}hPa")

Average Pressure for hour 1: 1011.95hPa
Average Pressure for hour 2: 1013.33hPa
Average Pressure for hour 3: 1012.08hPa
Average Pressure for hour 4: 1013.08hPa
Average Pressure for hour 5: 1008.70hPa
Average Pressure for hour 6: 1011.23hPa
Average Pressure for hour 7: 1010.80hPa
Average Pressure for hour 8: 1011.07hPa
Average Pressure for hour 9: 1012.40hPa
Average Pressure for hour 10: 1011.90hPa
Average Pressure for hour 11: 1011.62hPa
Average Pressure for hour 12: 1010.92hPa
Average Pressure for hour 13: 1009.40hPa
Average Pressure for hour 14: 1011.75hPa
Average Pressure for hour 15: 1013.33hPa
Average Pressure for hour 16: 1011.73hPa
Average Pressure for hour 17: 1012.83hPa
Average Pressure for hour 18: 1012.00hPa
Average Pressure for hour 19: 1015.85hPa
Average Pressure for hour 20: 1012.32hPa
Average Pressure for hour 21: 1009.17hPa
Average Pressure for hour 22: 1012.43hPa
Average Pressure for hour 23: 1010.68hPa
Average Pressure for hour 24: 1011.40hPa


In [40]:
temp_anomaly = temp < 25
for i in range(len(temp_anomaly)):
    if temp_anomaly[i]:
        print(f"Temperature anomaly detected at minute {i}: {temp[i]}°C")

Temperature anomaly detected at minute 0: 24°C
Temperature anomaly detected at minute 3: 21°C
Temperature anomaly detected at minute 5: 20°C
Temperature anomaly detected at minute 6: 15°C
Temperature anomaly detected at minute 7: 19°C
Temperature anomaly detected at minute 10: 24°C
Temperature anomaly detected at minute 11: 21°C
Temperature anomaly detected at minute 13: 21°C
Temperature anomaly detected at minute 14: 21°C
Temperature anomaly detected at minute 15: 23°C
Temperature anomaly detected at minute 16: 22°C
Temperature anomaly detected at minute 17: 22°C
Temperature anomaly detected at minute 18: 22°C
Temperature anomaly detected at minute 19: 23°C
Temperature anomaly detected at minute 23: 12°C
Temperature anomaly detected at minute 25: 14°C
Temperature anomaly detected at minute 26: 22°C
Temperature anomaly detected at minute 28: 12°C
Temperature anomaly detected at minute 29: 23°C
Temperature anomaly detected at minute 30: 15°C
Temperature anomaly detected at minute 31: 14

In [41]:
min_temp = np.min(temp)
time_for_min_temp = np.where(temp == min_temp)[0][0]
print(f"Minimum temperature of {min_temp}°C occurred at minute {time_for_min_temp}.")


Minimum temperature of 7°C occurred at minute 993.
