In [2]:
import numpy as np

1. Data Generation:

In [3]:
#Create a NumPy array for time_in_minutes from 0 to 1439 (24 hours * 60 minutes).
time_in_minuts = np.arange(1440)
print(time_in_minuts)

[   0    1    2 ... 1437 1438 1439]


In [8]:
#Generate synthetic temperature data: a base temperature (e.g., 22°C) with some random fluctuations (use np.random.normal).
#0 --> start 1 --> standard deviation and generate 1440 values one for each minute in the 24 hours
base_temp = 22
temp = np.random.normal(0,1,size=1440) 
print(temp)

[ 0.58635131  0.65513718 -0.03823749 ... -0.92341404 -0.0867282
 -2.06620114]


In [11]:
#Generate synthetic humidity data: a base humidity (e.g., 55%) with random fluctuations, ensuring values stay realistic (0-100%).
#Any value less than minimum becomes min_value and any value greater than maximum becomes max_value and values in between stay the same.
base_hum = 55
hum = np.random.normal(0,5,size=1440) + base_hum
hum = np.clip(hum,0,100)
print(hum)

[52.81029528 51.14383077 56.30468731 ... 62.34308003 59.94864366
 51.89659404]


In [10]:
#Generate synthetic pressure data: a base pressure (e.g., 1012 hPa) with random fluctuations.
base_pressure = 1012
pressure = np.random.normal(0,2,size=1440)
print(pressure)

[-1.47938033  1.79649515 -2.79294697 ... -0.29857993 -4.15384612
  4.41363253]


In [6]:
#Combine these into a single 2D NumPy array where each row represents a minute and columns are [time, temperature, humidity, pressure].
comb_data = np.column_stack((time_in_minuts,temp,hum,pressure))
print(comb_data)

[[ 0.00000000e+00  1.70000386e+00  6.09812482e+01 -6.43826497e-01]
 [ 1.00000000e+00 -3.22382643e-01  5.62611448e+01  1.93001530e+00]
 [ 2.00000000e+00 -1.26003371e+00  5.83948152e+01  1.40012210e+00]
 ...
 [ 1.43700000e+03  1.83241395e+00  5.73847854e+01  1.03034704e+00]
 [ 1.43800000e+03 -3.36007351e-01  5.26614846e+01  2.73189743e+00]
 [ 1.43900000e+03  2.62476294e-01  5.65523468e+01 -3.53433181e+00]]


2. Basic Statistics:

In [7]:
#Calculate the average, minimum, maximum temperature, humidity, and pressure for the entire 24-hour period.
avg_temp = np.mean(temp)
print("Avg temprature is:", avg_temp)
min_temp = np.min(temp)
print("Min temprature is:", min_temp)
max_temp = np.max(temp)
print("Max temprature is:", max_temp)

avg_humidity = np.mean(hum)
print("Avg humidity is:", avg_humidity)
min_humidity = np.min(hum)
print("Min humidity is:", min_humidity)
max_humidity = np.max(hum)
print("Max humidity is:", max_humidity)

avg_pressure = np.mean(pressure)
print("Avg pressure is:", avg_pressure)
min_pressure = np.min(pressure)
print("Min pressure is:", min_pressure)
max_pressure = np.max(pressure)
print("Max pressure is:", max_pressure)

Avg temprature is: -0.01607100946107916
Min temprature is: -3.2931938773936986
Max temprature is: 3.079516134210938
Avg humidity is: 54.9881250032439
Min humidity is: 37.660558045610756
Max humidity is: 71.82249678929193
Avg pressure is: -0.014405718856169786
Min pressure is: -6.144358866510921
Max pressure is: 6.3462940053534735


In [12]:
#Find the standard deviation for each of these parameters.
std_temp = np.std(temp)
print("Temparture standard deviation is:",std_temp)
std_humidity = np.std(hum)
print("Humidity standard deviation is:",std_humidity)
std_pressure = np.std(pressure)
print("Pressure standard deviation is:",std_pressure)

Temparture standard deviation is: 0.9995999651809164
Humidity standard deviation is: 5.08507266872832
Pressure standard deviation is: 2.030772118473159


3. Hourly Averages:

In [9]:
#Reshape the data (or use slicing/aggregation) to calculate the average temperature, humidity, and pressure for each hour of the day.
#You should end up with 24 average values for each parameter (24*60=1440min)
temp_in_hour = temp.reshape(24,60)
print(temp_in_hour)
hum_in_hour = hum.reshape(24,60)
print(hum_in_hour)
pressure_in_hour = pressure.reshape(24,60)
print(pressure_in_hour)

#Calculate the avg
temp_avg_in_hour = np.mean(temp_in_hour,axis=1)
print(temp_avg_in_hour)
hum_avg_in_hour = np.mean(hum_in_hour,axis=1)
print(hum_avg_in_hour)
pressure_avg_in_hour = np.mean(pressure_in_hour,axis=1)
print(pressure_avg_in_hour)

[[ 1.70000386 -0.32238264 -1.26003371 ...  2.09434341 -1.0743181
  -0.21589707]
 [-0.21580677 -0.53635731  1.01686043 ... -1.66513823 -1.93076457
   0.25741609]
 [ 1.64768737 -0.9455606   0.07021885 ... -0.84225537  0.86134638
  -0.98682466]
 ...
 [ 0.2777638   0.73189424  0.82949012 ... -0.32100927 -1.02734796
   2.97415936]
 [-2.03778408 -0.10312714 -0.57282131 ...  0.9292685   1.88147449
   0.0443436 ]
 [ 0.4364547   1.78017004  0.04544673 ...  1.83241395 -0.33600735
   0.26247629]]
[[60.98124824 56.26114479 58.39481517 ... 57.56906991 57.94502344
  53.73460503]
 [51.57139108 55.46469082 51.58094022 ... 56.45382461 56.93717005
  62.38482287]
 [59.49765602 61.2637917  53.70157383 ... 54.64197779 64.50742586
  57.00687864]
 ...
 [53.06122879 57.29310715 51.25411748 ... 47.28669464 53.42159685
  56.31833672]
 [54.38845428 55.45928085 52.98506897 ... 62.9803452  62.53404253
  52.74557931]
 [61.43756445 59.86151071 54.16206524 ... 57.38478539 52.66148461
  56.55234678]]
[[-0.6438265   1.

4. Anomaly Detection (Simple):

In [13]:
#Identify and count how many minutes the temperature exceeded a certain threshold (e.g., 25°C).
anomalies = time_in_minuts [temp > 25]
anomalies_num = len(anomalies)

#Find the time (in minutes) when the minimum temperature occurred.
min_temp_and_time = time_in_minuts [np.argmin(temp)] #function that returns index of minimum value in an array
min_temp_in_hour = min_temp_and_time // 60
min_temp_in_minute = min_temp_and_time % 60
print(f"Min temperature occurred at minute {min_temp_and_time} → {min_temp_in_hour:02d}:{min_temp_in_minute:02d}")

Min temperature occurred at minute 428 → 07:08


In [11]:
#Save the combined 2D array to a .csv file using NumPy's saving functions.
np.savetxt("environmental_condition_data.csv", comb_data, delimiter=",",
           header="Time(min),Temperature(°C),Humidity(%),Pressure(hPa)", comments='')
#Data exported successfully as .csv file 