**Part 1: Array Creation and Properties**

1- Create a 1D array named arr1d with integers from 0 to 9.

In [1]:
import numpy as np

In [2]:
arr1d = np.arange(10)
print(arr1d)

[0 1 2 3 4 5 6 7 8 9]


2- Create a 2D array named arr2d with shape (3, 3) filled with ones.

In [4]:
arr2d = np.ones((3,3))
print(arr2d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


3- Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.

In [7]:
random_matrix = np.random.randn(3,3)
print(random_matrix)

[[-1.97523752  0.49815531 -0.23358217]
 [-0.03399026 -0.14227621  0.48222329]
 [ 0.52306656 -0.71639677  1.49107937]]


4- Create an array named even_numbers containing even numbers from 10 to 50 (inclusive).

In [11]:
even_numbers = np.arange(10,51,2)
print(even_numbers)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


5- Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).

In [12]:
linspace_array = np.linspace(0,1,7)
print(linspace_array)

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


6- Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array shape:", arr.shape)
print("Array dimension:", arr.ndim)
print("Array data type:", arr.dtype)

Array shape: (2, 3)
Array dimension: 2
Array data type: int64


**Part 2: Array Manipulation**

1- Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.

In [14]:
reshaped_arr = arr1d.reshape((2,5))
print(reshaped_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


2- Transpose reshaped_arr (from Q7). Name the result transposed_arr.

In [16]:
transposed_arr = reshaped_arr.T
print(transposed_arr)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


3- Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.

In [17]:
a = np.array([1,2,3])
b = np.array([4,5,6])
v_stack = np.vstack((a,b))
print("Vertical stack:\n",v_stack)

Vertical stack:
 [[1 2 3]
 [4 5 6]]


4- Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.

In [19]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])
h_stack = np.hstack((m1,m2))
print("Horizontal stack:\n",h_stack)

Horizontal stack:
 [[1 2 5 6]
 [3 4 7 8]]


5- Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.

In [20]:
arr_to_split = np.arange(16).reshape(4,4)
splited_part = np.hsplit(arr_to_split,2)
left_split = splited_part[0]
right_split = splited_part[1]
print("Left split is:\n",left_split)
print("\nRight split is:\n",right_split)

Left split is:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

Right split is:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


6- Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.

In [21]:
arr_to_split = np.arange(16).reshape(4,4)
parts = np.vsplit(arr_to_split,2)
upper_rows = parts[0]
lower_rows = parts[1]
print("Upper rows is:\n",upper_rows)
print("\nLower rows is:\n",lower_rows)

Upper rows is:
 [[0 1 2 3]
 [4 5 6 7]]

Lower rows is:
 [[ 8  9 10 11]
 [12 13 14 15]]


**Part 3: Indexing, Slicing, and Boolean Indexing**

1- Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.

In [22]:
data = np.array([[10,11,12],[13,14,15],[16,17,18]])
extracted_element = data[1,2]
print(extracted_element)

15


2- From the data array (from Q13), extract the first two rows and all columns.

In [23]:
data = np.array([[10,11,12],[13,14,15],[16,17,18]])
extracted_element = data[:2 , : ]
print(extracted_element)

[[10 11 12]
 [13 14 15]]


3- From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).

In [24]:
data = np.array([[10,11,12],[13,14,15],[16,17,18]])
data_11 = [0,1]
data_15 = [1,2]
data_17 = [2,1]
rows = [0,1,2]
column = [1,2,1]
extracted_element = data[rows,column]
print(extracted_element)

[11 15 17]


4- Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.

In [26]:
scores = np.array([85,92,78,65,95,88])
print("Original scores:\n", scores)
condition = scores>80
print("\nBoolean scores:\n", condition)

Original scores:
 [85 92 78 65 95 88]

Boolean scores:
 [ True  True False False  True  True]


**Part 4: Numerical Operations and Aggregations**

1- Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).

In [29]:
arr_op1 = np.array([10,20,30])
arr_op2 = np.array([2,4,6])
arr_mul = arr_op1 * arr_op2 
arr_div = arr_op1 / arr_op2 
print("Multiplication operation result:\n", arr_mul)
print("\nDivision operation result:\n",arr_div)

Multiplication operation result:
 [ 20  80 180]

Division operation result:
 [5. 5. 5.]


2- Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculatethe sum of all elements in the matrix.

In [30]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr_sum = matrix.sum()
print("Sum result:\n", arr_sum)

Sum result:
 45


3- From the matrix (from Q18), calculate the mean of each column.

In [33]:
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
columns_mean = np.mean(matrix, axis = 0)
print("Mean value:\n", columns_mean)

Mean value:
 [4. 5. 6.]


4- Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.

In [35]:
price_array = np.array([100,150,200,250])
discount_percentage = 0.10
result = price_array *(1 - discount_percentage)
print("Result:\n", result)

Result:
 [ 90. 135. 180. 225.]
