Array Creation and Properties

In [85]:
import numpy as np
arr1d = np.arange(10)
arr1d 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:

arr2d = np.ones((3,3))
arr2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [88]:
random_matrix = np.random.randn(3,3)
random_matrix

array([[-0.25860429, -0.23145205, -1.51987982],
       [ 0.57336306, -0.24448677,  2.07853984],
       [-1.29972121,  0.70173206, -1.0285794 ]])

In [89]:
even_numbers = np.arange(10, 50, 2)
even_numbers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [90]:
linspace_array = np.linspace(0, 1, 7)
linspace_array

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [91]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print("shape:", arr.shape)
print("dtype:" , arr.dtype)
print("ndim:" , arr.ndim)

[[1 2 3]
 [4 5 6]]
shape: (2, 3)
dtype: int64
ndim: 2


Array Manipulation 

In [92]:
reshaped_arr = arr1d.reshape((2, 5))
print("reshaped_arr:\n", reshaped_arr)

reshaped_arr:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [93]:
transposed_arr = reshaped_arr.T
print("transposed_arr:\n", transposed_arr)


transposed_arr:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [94]:
a = np.array([1,2,3])
b = np.array([4,5,6])
stack_vertically = np.vstack((a,b))
print("stack_vertically:\n", stack_vertically)

stack_vertically:
 [[1 2 3]
 [4 5 6]]


In [95]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])
stack_horizontally = np.hstack((m1,m2))
print("stack_horizontal:\n", stack_horizontally)

stack_horizontal:
 [[1 2 5 6]
 [3 4 7 8]]


In [96]:
arr_to_split = np.arange(16).reshape(4,4)
split_horizontal = np.hsplit(arr_to_split, 2)
print("Split horizontally into 2 parts:\n")
print("part 1:\n",split_horizontal[0])
print("part 2:\n",split_horizontal[1])

Split horizontally into 2 parts:

part 1:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
part 2:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [97]:
split = np.vsplit(arr_to_split, 2)
print("split vertically at index 2:\n")
print("part 1: \n",split[0])
print("part 2: \n",split[1])

split vertically at index 2:

part 1: 
 [[0 1 2 3]
 [4 5 6 7]]
part 2: 
 [[ 8  9 10 11]
 [12 13 14 15]]


Indexing, Slicing, and Boolean Indexing

In [98]:
Given_data = np.array([[10,11,12],
                       [13,14,15],
                       [16,17,18]])
extract_element = Given_data[1,2]
print("ectract element:\n",extract_element)

ectract element:
 15


In [99]:
Extract_elem = Given_data[:2,:]
print("extract:\n", Extract_elem)

extract:
 [[10 11 12]
 [13 14 15]]


In [100]:
rows = [0,1,2]
cols = [1,2,1]
part_t = Given_data[rows,cols]
part_t

array([11, 15, 17])

In [101]:
Given_scores = np.array([85, 92, 78, 65, 95, 88])
condition = Given_scores [Given_scores> 80 ]
print("Scores greater than 80:\n", condition)

Scores greater than 80:
 [85 92 95 88]


Numerical Operations and Aggregations

In [103]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])
multiplication = arr_op1 * arr_op2
division = arr_op1 / arr_op2
print("multiplication of arr_op1 and arr_op2: \n", multiplication)
print("division of arr_op1 and arr_op2: \n", division)

multiplication of arr_op1 and arr_op2: 
 [ 20  80 180]
division of arr_op1 and arr_op2: 
 [5. 5. 5.]


In [104]:
Given_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
calculate_sum = np.sum (Given_matrix)
calculate_sum

np.int64(45)

In [105]:
Given_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
get_mean = np.mean(Given_matrix , axis=0)
get_mean

array([4., 5., 6.])

In [106]:
Given_price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10
apply = Given_price_array * (1 - discount_percentage)
apply

array([ 90., 135., 180., 225.])