In [140]:
import numpy as np

Array Creation and properties

In [141]:
arr1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr1d)

[0 1 2 3 4 5 6 7 8 9]


In [142]:
arr2d = np.ones((3, 3))
print(arr2d)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [143]:
random_matrix = np.random.randn(3, 3)
print(random_matrix)

[[-0.66614677  0.27791991  0.77114963]
 [ 0.79591044 -1.93880155  0.99567566]
 [ 0.75218314  0.5216301   1.16768875]]


In [144]:
evennumbers = np.arange(10, 20, 2)
print(evennumbers)

[10 12 14 16 18]


In [145]:
lineSpace_array = np.linspace(0, 1, 7)
print(lineSpace_array)

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [146]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
shape = arr.shape
print(shape)
dtype = arr.dtype
print(dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


Array Manipulation

In [147]:
reshape = arr1d.reshape(2, 5)
print(reshape)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [148]:
transpose = reshape.T
print(transpose) 

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [149]:
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6])
stake = np.stack((a, b), axis=0)
print(stake)

[[1 2 3]
 [4 5 6]]


In [150]:
m1 = np.array([[1, 2], [3, 4]]) 
m2 = np.array([[5, 6], [7, 8]])
hstake = np.hstack((m1, m2))
print(hstake)

[[1 2 5 6]
 [3 4 7 8]]


In [151]:
arr_to_split = np.arange(16).reshape(4, 4)
part1, part2 = np.hsplit(arr_to_split, 2,)
print(part1)
print(part2)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [152]:
part1, part2 = np.vsplit(arr_to_split, 2,)
print(part1)
print(part2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


 Indexing, Slicing, and Boolean Indexing

In [153]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
element = data[0, 1]
print(element)

11


In [154]:
element2 = data[:2,:]
print(element2)

[[10 11 12]
 [13 14 15]]


In [155]:
element3 = data[(0, 1, 2),(1, 2, 1)]
print(element3)

[11 15 17]


In [156]:
scores = np.array([85, 92, 78, 65, 95, 88])
high_scores = scores[scores > 80]
print(high_scores)

[85 92 95 88]


Numerical Operations and Aggregations

In [157]:
arr_op1 = np.array([10, 20, 30]) 
arr_op2 = np.array([2, 4, 6])
arr_multiply = arr_op1 * arr_op2
arr_divide = arr_op1 / arr_op2
print(arr_multiply)    
print(arr_divide)

[ 20  80 180]
[5. 5. 5.]


In [158]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_sum = np.sum(matrix)
print(matrix_sum)  

45


In [159]:
mean = np.mean(matrix, axis=0)
print(mean)

[4. 5. 6.]


In [160]:
price_array = np.array([100, 150, 200, 250])
discount = 0.1
discount = price_array * (1 - discount)
print(discount)

[ 90. 135. 180. 225.]
