## Part 1: Array Creation and Properties

1- Create a 1D array named arr1d with integers from 0 to 9.

In [197]:
import numpy as np
arr1d = np.arange(10)
print("arr1d:", arr1d)


arr1d: [0 1 2 3 4 5 6 7 8 9]


2- Create a 2D array named arr2d with shape (3, 3) filled with ones.

In [198]:
arr2d = np.ones((3, 3))
print("arr2d:\n", arr2d)


arr2d:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


3- Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.

In [199]:
random_matrix = np.random.randn(3, 3)
print("random_matrix:\n", random_matrix)


random_matrix:
 [[-0.62087687  1.78916665  0.60438277]
 [-1.31859903 -0.65513394  0.42316964]
 [-0.14283571 -0.35324435  0.35326695]]


4- Create an array named even_numbers containing even numbers from 10 to 50 (inclusive).

In [200]:
even_numbers = np.arange(10, 51, 2)
print("even_numbers:", even_numbers)


even_numbers: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


5- Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).

In [201]:
linspace_array = np.linspace(0, 1, 7)
print("linspace_array:", linspace_array)


linspace_array: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


6- Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.

In [202]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Data type:", arr.dtype)


Shape: (2, 3)
Number of dimensions: 2
Data type: int64


## Part 2: Array Manipulation

7- Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.

In [203]:
reshaped_arr = arr1d.reshape(2, 5)
print("reshaped_arr:\n", reshaped_arr)


reshaped_arr:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


8- Transpose reshaped_arr (from Q7). Name the result transposed_arr.

In [204]:
transposed_arr = reshaped_arr.T
print("transposed_arr:\n", transposed_arr)


transposed_arr:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


9- Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.

In [205]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_vertical = np.vstack((a, b))
print("Vertically stacked:\n", stacked_vertical)


Vertically stacked:
 [[1 2 3]
 [4 5 6]]


10- Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.

In [206]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
stacked_horizontal = np.hstack((m1, m2))
print("Horizontally stacked:\n", stacked_horizontal)


Horizontally stacked:
 [[1 2 5 6]
 [3 4 7 8]]


11- Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.

In [207]:
arr_to_split = np.arange(16).reshape(4, 4)
left_part, right_part = np.hsplit(arr_to_split, 2)
print("Left half:\n", left_part)
print("Right half:\n", right_part)


Left half:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Right half:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


12- Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.

In [208]:
top_part, bottom_part = np.vsplit(arr_to_split, 2)
print("Top half:\n", top_part)
print("Bottom half:\n", bottom_part)


Top half:
 [[0 1 2 3]
 [4 5 6 7]]
Bottom half:
 [[ 8  9 10 11]
 [12 13 14 15]]


## Part 3: Indexing, Slicing, and Boolean Indexing

13- Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.

In [209]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print("Element at row 1, col 2:", data[1, 2])


Element at row 1, col 2: 15


14- From the data array (from Q13), extract the first two rows and all columns.

In [210]:
print("First two rows:\n", data[:2, :])


First two rows:
 [[10 11 12]
 [13 14 15]]


15- From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).

In [211]:
rows = [0, 1, 2]
cols = [1, 2, 1]
fancy = data[rows, cols]
print("Fancy indexed elements:", fancy)


Fancy indexed elements: [11 15 17]


16- Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.

In [212]:
scores = np.array([85, 92, 78, 65, 95, 88])
high_scores = scores[scores > 80]
print("Scores > 80:", high_scores)


Scores > 80: [85 92 95 88]


## Part 4: Numerical Operations and Aggregations

17- Perform element-wise multiplication and division.

In [213]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])
print("Multiplication:", arr_op1 * arr_op2)
print("Division:", arr_op1 / arr_op2)


Multiplication: [ 20  80 180]
Division: [5. 5. 5.]


18- Calculate the sum of all elements in the matrix.

In [214]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
total_sum = np.sum(matrix)
print("Sum of all elements:", total_sum)


Sum of all elements: 45


19- Calculate the mean of each column in the matrix.

In [215]:
column_mean = np.mean(matrix, axis=0)
print("Mean of each column:", column_mean)


Mean of each column: [4. 5. 6.]


20- Apply a 10% discount to all prices.

In [216]:
price_array = np.array([100, 150, 200, 250])
discounted = price_array * (1 - 0.10)
print("Prices after 10% discount:", discounted)


Prices after 10% discount: [ 90. 135. 180. 225.]
